### ISSUE TITLE
allow iterating to previous occurrence [sf#4]

### ISSUE THREAD

**Issue by winterz** [libical/libical#103]
Currently, the only possible iteration between occurrences is to use icalrecur_iterator_next() to iterate to the next occurrence.

Similarly, there should be an icalrecur_iterator_prev() to iterate backwards. This could be used to get the previous occurrence of an item, given the occurrence.

This is needed to get rid of some workarounds with Mozilla Sunbird/Lightning.

Please go ahead and take over. I have attached a work in progress patch (untested, but compiles) but have no time to continue on this feature.

**Comment by ksmurchison** [comment]
Allen, where is your patch for this?

**Comment by winterz** [comment]
it isn't mine, but I found it.  it looks like mine because the sourceforge issue importer makes it look like all the old issues belong to me.

the patch is rather large so I'll like to it:
https://sourceforge.net/p/freeassociation/feature-requests/4/
https://sourceforge.net/p/freeassociation/feature-requests/_discuss/thread/69b61618/2061/attachment/icalrecur-prev-occurrence.diff

**Comment by winterz** [comment]
Ken, I know you did quite some work on iterating.  what should we do with this isse?

**Comment by ksmurchison** [comment]
Is there a big audience and/or use for this?

--
Kenneth Murchison
Principal Systems Software Engineer
Carnegie Mellon University

**Comment by winterz** [comment]
I don't think so.  The original request was made in 2008. Not a release blocker.

**Comment by ksmurchison** [comment]
Implemented here: https://github.com/libical/libical/commit/c332a62d33bb7ef44e0530a29c7768205cd841f3

@winterz @ksuther  We need to decide if we need/want new functions to set the start/end points of the reverse iterator.  The current code starts from wherever the forward iterator left off. 
Is there a use case to iterate backwards from UNTIL or some other time in the future without iterating forward first?

**Comment by ksmurchison** [comment]
Added icalrecur_iterator_set_range() to set  to/from for both forward and backward iteration:
https://github.com/libical/libical/commit/f9416a172bface34683d3f2aafca552fcddede08

**Comment by ksmurchison** [comment]
@winterz I'd love to get a review of my feature branch.  It shouldn't break any existing code

**Comment by minichma** [comment]
> Is there a use case to iterate backwards from UNTIL or some other time in the future without iterating forward first?

@ksmurchison One use case is related to time zones: Finding the latest time change before a given time T, so we can find out the current time offset.

**Comment by winterz** [comment]
@ksmurchison I just pushed a few minor fixes to the icalrecur_iterator_prev branch. also added to the Releases Notes.
You can merge to the master branch.
Great stuff!

**Comment by ksmurchison** [comment]
Done
