### ISSUE TITLE
Support importing vCalendar RRULEs [sf#7]

### ISSUE THREAD

**Issue by winterz** [libical/libical#106]
As some applications (Orage, in particular) use libical to import vCalendar format files, I would really appreciate if libical was able to read RRULEs in that format (as described in http://www.imc.org/pdi/vcal-10.txt ).

**Comment by winterz** [comment]
Ken, assigning this ancient bug to you since you are Mr. RRULE.
Thoughts about this one?

**Comment by ksmurchison** [comment]
Do we think/know if this functionality is still desired?

**Comment by winterz** [comment]
let's close it.
been many years since the initial request and we haven't heard any requests since then.
