### ISSUE TITLE
libical cannot show UTF-8 strings with icalparser_add_line() [sf#4]

### ISSUE THREAD

**Issue by winterz** [libical/libical#116]
libical cannot show UTF-8 strings with icalparser\_add\_line\(\) because strstriplt\(\) works for ASCII only.

To reproduce:
1\. cat a.ics
BEGIN:VCALENDAR
PRODID:-//Ximian//NONSGML Evolution Calendar//EN
VERSION:2.0
METHOD:PUBLISH
BEGIN:VEVENT
SUMMARY: xxx multi-byte xxx
LOCATION: xxx multi-byte xxx 
END:VEVENT
END:VCALENDAR

2\. run program.

icalparser \*parser = icalparser\_new\(\);
icalparser\_set\_gen\_data\(parser, fopen\("a.ics", "r"\)\);
line = icalparser\_get\_line\(parser,read\_stream\);

Then the UTF-8 SUMMARY and LOCATION are always garbaged.
I'm attaching the patch.

**Comment by winterz** [comment]
closing this.  I added a regression test for utf8 chars and it seems to work fine on all the platforms I can check. see commit a6e171ffdfb005a7b8b81623dc7e0c5818688245

**Comment by pusateri** [comment]
Trying to import this .ics file but having trouble with UTF8 strings. Specifically, the SUMMARY field of UID ical-ietf-93-3ce43c64.1@tools.ietf.org in the file is read incorrectly. Should be Žofín Palace.

http://tools.ietf.org/agenda/93/agenda_93.ics

**Comment by pusateri** [comment]
Update: This is working now on 1.0.1. It seems I was reading in the file incorrectly before passing it to libical for parsing. Sorry for the confusion. But feel free to use the input file above for testing. It will be at that URL permanently.

**Comment by winterz** [comment]
thanks for testing.
I added a regression test for the  Žofín Palace in the SUMMARY just in case.
