### ISSUE TITLE
Dropping invalid characters from parameters [sf#9]

### ISSUE THREAD

**Issue by winterz** [libical/libical#121]
As discussed on https://sourceforge.net/mailarchive/forum.php?thread\_name=20100110172736.GC4118%40bzzt.net&forum\_name=freeassociation-devel and https://sourceforge.net/mailarchive/forum.php?thread\_name=201001080806.49751.bradh%40frogmouth.net&forum\_name=freeassociation-devel , this patch removes some invalid characters when outputting parameters - for instance when a timezone contains a newline.

**Comment by ksmurchison** [comment]
Fixed with https://github.com/libical/libical/commit/c63af68b33accf16a5bd8ffc8464d80fe4338c60

**Comment by winterz** [comment]
Ken,
could you add a bullet to the ReleaseNotes about this?
also, I think we had a test in regression.c for this which is probably ifdef'd out. could you see if we can restore that test?
