### ISSUE TITLE
patch to support vcard in libical. [sf#15]

### ISSUE THREAD

**Issue by winterz** [libical/libical#127]
This patch enables libical to parse & generate vcard data (only v 3.0).
The patch modifies the design data to add vcard components, properties and parameters.

**Comment by winterz** [comment]
patch can be found at https://sourceforge.net/p/freeassociation/patches/_discuss/thread/df422708/832b/attachment/libical-vcard.diff

**Comment by winterz** [comment]
I'd be willing to see this added but I don't see any rfc or draft rfc associated with this. so for now I'm putting this off.

**Comment by dilyanpalauzov** [comment]
What does is mean, there is no RFC associated with this?

RFC 2426 defines vCard 3.0

**Comment by winterz** [comment]
someone gave me that patch many years ago.  I don't recall the use-case anymore, nor if there was any discussion about it.
Let's ignore this.
