### ISSUE TITLE
`icalvalue_new_from_string got an unknown value type`

### ISSUE THREAD

**Issue by paulepanter** [libical/libical#178]
[Evolution][] 3.12.7 prints the following libical warning to the terminal.

    /build/libical-Kva2cE/libical-1.0/src/libical/icalvalue.c:758: icalvalue_new_from_string got an unknown value type

Is there a way, to get what the value type actually is? Looking at the source, how can the more detailed error be looked at?

            if (error != 0 ){
		char temp[TMP_BUF_SIZE];
                
                snprintf(temp,TMP_BUF_SIZE,"Unknown type for \'%s\'",str);
			    
		*error = icalproperty_vanew_xlicerror( 
		    temp, 
		    icalparameter_new_xlicerrortype( 
			ICAL_XLICERRORTYPE_VALUEPARSEERROR), 
		    0); 
	    }

[Evolution]: https://wiki.gnome.org/Apps/Evolution/

**Comment by winterz** [comment]
this is fixed in the upcoming release version 2.0
the warning message will contain the value kind id as well as the value string. should help.
git commit 50ee7bd..1d1a5b3
