### ISSUE TITLE
Alarm's ATTACH is not written in version 1.0.1

### ISSUE THREAD

**Issue by jarvied** [libical/libical#179]
ArchLinux using libical 1.0.1-1 fails to write the ATTACH property when part of an alarm, but libical 1.0-3 works correctly. The code is:

    icalattach* attach = icalattach_new_from_url(filename);
    icalcomponent* a = icalcomponent_new(ICAL_VALARM_COMPONENT);
    icalcomponent_add_property(a, icalproperty_new_attach(attach));

This occurs in KDE 4.14.2 (libkdepim/kcalcore/icalformat_p.cpp in writeAlarm()). See https://bugs.kde.org/show_bug.cgi?id=340618.

**Comment by jarvied** [comment]
I tried to reproduce the reported bug using libical compiled from the 1.0.1 source, and could not reproduce the reported fault. Again, see https://bugs.kde.org/show_bug.cgi?id=340618.

**Comment by winterz** [comment]
Thanks David.  appreciate your time on this.
