### ISSUE TITLE
Using libical TZID correcly with iOS TZID

### ISSUE THREAD

**Issue by monkeyfdude** [libical/libical#184]
Please help me understand TIME ZONE processing

I see this in regression.c

```
	    icalcomponent_vanew(
		ICAL_VTIMEZONE_COMPONENT,
		icalproperty_new_tzid("America/New_York"),
		icalcomponent_vanew(
		    ICAL_XDAYLIGHT_COMPONENT,
		    icalproperty_new_dtstart(atime),
		    icalproperty_new_rdate(rtime),
		    icalproperty_new_tzoffsetfrom(-4),
		    icalproperty_new_tzoffsetto(-5),
		    icalproperty_new_tzname("EST"),
		    (void *)0),
		icalcomponent_vanew(
		    ICAL_XSTANDARD_COMPONENT,
		    icalproperty_new_dtstart(atime),
		    icalproperty_new_rdate(rtime),
		    icalproperty_new_tzoffsetfrom(-5),
		    icalproperty_new_tzoffsetto(-4),
		    icalproperty_new_tzname("EST"),
		    (void *)0),
```

I have following questions:

* icalproperty_new_tzid("America/New_York") has a string in it. I need to process this timezone in iOS. How will I make sure that this timezone string matches the timezone string provide by iOS apis?

* How will ICAL_XDAYLIGHT_COMPONENT be used?
* What was the need to the above.

**Comment by ksmurchison** [comment]
This is better discussed on the developer mailing list, not by opening a bug
http://lists.infradead.org/mailman/listinfo/libical-devel
