### ISSUE TITLE
possible segfault in fetch_lat_long_from_string (src/libical/icaltimezone.c) (and maybe other)

### ISSUE THREAD

**Issue by echampet** [libical/libical#194]
Hi,

i'm a little rusty in C, but scan-build spotted an error in https://github.com/libical/libical/blob/coverity_scan/src/libical/icaltimezone.c#L1634
```
lon = lat + 1;
while (*lon != '+' && *lon != '-')
        lon++;
```
the error is *lon can be garbage.
in all loops in the function we never check for '\0' (or assert),
so we can easily read after what we own -> segfault ...

i think we should recheck all loops with negative conditions (i don't have the time right now)

**Comment by winterz** [comment]
good catch by scan-build.  easy enough to fix.  checking all the loops by eye isn't fun, but if build-scan helps out i'm happy to fix all the issues it can find. or happy to merge your fixes.

do you want me to fix this one or do you intend to do that?

**Comment by echampet** [comment]
Hi,
i'm short on time right now,
and i don't know when it's best to assert or recover from bad input
I'll let you do you magic :) for this (these?) one

**Comment by winterz** [comment]
I ran scan-build and cleaned-up everything worth fixing.
closing this one.
