### ISSUE TITLE
Use GNUInstallDirs

### ISSUE THREAD

**Issue by tintou** [libical/libical#195]
It would be a nice move to use GNUInstallDirs on non-windows platforms
http://www.cmake.org/cmake/help/git-master/module/GNUInstallDirs.html
This makes the packaging easier and the CMake files smaller.

**Comment by winterz** [comment]
good idea.
feel like making a patch for this?

**Comment by tintou** [comment]
Done here https://github.com/libical/libical/pull/196

**Comment by winterz** [comment]
your patch was merged. thanks.
