### ISSUE TITLE
icalparser_parse_string leaks memory

### ISSUE THREAD

**Issue by monkeyfdude** [libical/libical#209]
I use libical.a provided by XbICalendar in iOS app. Following line leaks memory as per XCODE

```
    icalcomponent *root = icalparser_parse_string([content cStringUsingEncoding:NSUTF8StringEncoding]);
    icalcomponent_free(root);


```
   0 libsystem_malloc.dylib malloc_zone_malloc
   1 libsystem_malloc.dylib malloc
   2 EX icalmemory_new_buffer /work/AndrewHalls/libical/scripts/libical/src/libical/icalmemory.c:262
   3 EX make_segment /work/AndrewHalls/libical/scripts/libical/src/libical/icalparser.c:222
   4 EX parser_get_param_name /work/AndrewHalls/libical/scripts/libical/src/libical/icalparser.c:287
   5 EX icalparser_add_line /work/AndrewHalls/libical/scripts/libical/src/libical/icalparser.c:884
   6 EX icalparser_parse /work/AndrewHalls/libical/scripts/libical/src/libical/icalparser.c:629
   7 EX icalparser_parse_string /work/AndrewHalls/libical/scripts/libical/src/libical/icalparser.c:1343
   8 EX +[XbICComponent componentWithString:] 
```
```

https://github.com/libical/XbICalendar/issues/31

**Comment by monkeyfdude** [comment]
Hello,

Can you please provide some information on this issue?

**Comment by ahalls** [comment]
I think I've fixed the issue by updating the code used to build the libical library in the XbICalendar distrubution.   This build is using the code in the 1.0.1 tag.   

Let me know if this does not resolve your issue and I'll take another look.
