### ISSUE TITLE
BYSETPOS in RRULE seems to be ignored [sf#21]

### ISSUE THREAD

**Issue by winterz** [libical/libical#21]
Using one of rfc2445's examples \(from page 43 of the rfc\):
"the last work day of the month" could be represented as:
RRULE:FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1

If I create a rule to do this using:
struct icalrecurrencetype recur =
icalrecurrencetype\_from\_string\("FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1"\);
struct icaltimetype dtstart =
icaltime\_from\_string\("20040527"\);
icalrecur\_iterator\* ritr =
icalrecur\_iterator\_new\(recur, dtstart\);

If I iterate through it, the next few occurences I get are:
20040527
20040528
20040531
20040601
20040602
20040603
20040604
20040607
20040608
20040609
20040610
20040611

This seems to be ignoring the BYSETPOS=-1, and just
generating occurences for each day, rather than the
last work day of the month.

If I use the same code as above, but instead use the
recurrence:
icalrecurrencetype\_from\_string\("FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR"\);

then I get exactly the same sequence of occurences as
shown above, regardless of the fact that BYSETPOS isn't
present.

Dave

**Comment by ksmurchison** [comment]
This is fixed in master:

RRULE:FREQ=MONTHLY;COUNT=12;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1
DTSTART:20040527
INSTANCES:20040531,20040630,20040730,20040831,20040930,20041029,20041130,20041231,20050131,20050228,20050331,20050429

**Comment by winterz** [comment]
closing then
