### ISSUE TITLE
about the icalcomponent_foreach_recurrence

### ISSUE THREAD

**Issue by nyz110** [libical/libical#213]
BEGIN:VCALENDAR
PRODID:-//ACME/DesktopCalendar//EN
METHOD:REQUEST
VERSION:2.0
BEGIN:VEVENT
DTSTART:19700308T020000
DTEND:19970701T190000Z
ORGANIZER:Mailto:A@example.com
ATTENDEE;ROLE=CHAIR;PARTSTAT=ACCEPTED;CUTYPE=INDIVIDUAL:A@example.COM
ATTENDEE;RSVP=TRUE;CUTYPE=INDIVIDUAL:B@example.fr
ATTENDEE;RSVP=TRUE;CUTYPE=INDIVIDUAL:c@example.jp
DTSTAMP:19970613T190030Z
DTSTART;TZID=America-SanJose:19970701T140000
DTEND;TZID=America-SanJose:19970701T150000
RRULE:FREQ=DAILY;INTERVAL=2;WKST=SU
SUMMARY:Dayly Phone Conference
UID:calsrv.example.com-873970198738780@example.com
SEQUENCE:0
STATUS:CONFIRMED
END:VEVENT
END:VCALENDAR

above is my ics file content,when I call icalcomponent_foreach_recurrence to calculate recurrences between 2015/8/1(start) and 2015/8/31(end) .but callback method was called 5000 times. I log the reuslt ,it return icaltime_span struct ,first result  {start:1997-3-8 end:2015-8-1},4000items ,last result{start:2015-8-31,end:2032-x-x} .and i want result is:first{start:2015-8-1 end:2015-8-1},{start:2015-8-3 end:2015-8-3}..last{start:2015-8-31,end2015-8-31}.do i have something wrong on calling the foreach method? I do not know how to resolve it  .

**Comment by ksmurchison** [comment]
Looking at the iCalendar data, it contains two sets of DTSTART/DTEND.  
I'm sure this is what is confusing libical, since the first set 
(probably from a VTIMEZONE component) says that the event lasts for 27 
years.  The second set looks more reasonable since it shows a 1 hr event.


On 08/20/2015 02:57 AM, nyz110 wrote:
>
> BEGIN:VCALENDAR
> PRODID:-//ACME/DesktopCalendar//EN
> METHOD:REQUEST
> VERSION:2.0
> BEGIN:VEVENT
> DTSTART:19700308T020000
> DTEND:19970701T190000Z
> ORGANIZER:Mailto:A@example.com <mailto:A@example.com>
> ATTENDEE;ROLE=CHAIR;PARTSTAT=ACCEPTED;CUTYPE=INDIVIDUAL:A@example.COM 
> <mailto:A@example.COM>
> ATTENDEE;RSVP=TRUE;CUTYPE=INDIVIDUAL:B@example.fr <mailto:B@example.fr>
> ATTENDEE;RSVP=TRUE;CUTYPE=INDIVIDUAL:c@example.jp <mailto:c@example.jp>
> DTSTAMP:19970613T190030Z
> DTSTART;TZID=America-SanJose:19970701T140000
> DTEND;TZID=America-SanJose:19970701T150000
> RRULE:FREQ=DAILY;INTERVAL=2;WKST=SU
> SUMMARY:Dayly Phone Conference
> UID:calsrv.example.com-873970198738780@example.com 
> <mailto:calsrv.example.com-873970198738780@example.com>
> SEQUENCE:0
> STATUS:CONFIRMED
> END:VEVENT
> END:VCALENDAR
>
> above is my ics file content,when I call 
> icalcomponent_foreach_recurrence to calculate recurrences between 
> 2015/8/1(start) and 2015/8/31(end) .but callback method was called 
> 5000 times. I log the reuslt ,it return icaltime_span struct ,first 
> result {start:1997-3-8 end:2015-8-1},4000items ,last 
> result{start:2015-8-31,end:2032-x-x} .and i want result 
> is:first{start:2015-8-1 end:2015-8-1},{start:2015-8-3 
> end:2015-8-3}..last{start:2015-8-31,end2015-8-31}.do i have something 
> wrong on calling the foreach method? I do not know how to resolve it .
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/libical/libical/issues/213>.
>


-- 
Kenneth Murchison
Principal Systems Software Engineer
Carnegie Mellon University

**Comment by nyz110** [comment]
thanks for ksmurchison' reply.
yes,i find why，the method is right，the event lasts for 27 years, so a lot of occurrences callback whose occur timespan(start,end)  contain the range i have passed(starttime,endtime). but i want ignore the event's end date when calculate recurrences,like iCal4j framework calculate without dtend .now i solve it ,just before calling the  method icalcomponent_foreach_recurrence,set the event component dtend equal to dtstart :
struct icaltimetype dtstart =  icalcomponent_get_dtstart(eventComp);
icalcomponent_set_dtend(eventComp, dtstart);
if others have the same demand ,you can do as me.

**Comment by ksmurchison** [comment]
I think you missed my point.  iCalendar data with multiple DTSTART/DTEND 
is bad data.  Technically libical should be rejecting the data.


On 08/20/2015 09:49 PM, nyz110 wrote:
>
> thanks for ksmurchison' reply.
> yes,i find why，the method is right，the event lasts for 27 years, so 
> a lot of occurrences callback whose occur timespan(start,end) contain 
> the range i have passed(starttime,endtime). but i want ignore the 
> event's end date when calculate recurrences,like iCal4j framework 
> calculate without dtend .now i solve it ,just before calling the 
> method icalcomponent_foreach_recurrence,set the event component dtend 
> equal to dtstart :
> struct icaltimetype dtstart = icalcomponent_get_dtstart(eventComp);
> icalcomponent_set_dtend(eventComp, dtstart);
> if others have the same demand ,you can do as me.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/libical/libical/issues/213#issuecomment-133244272>.
>


-- 
Kenneth Murchison
Principal Systems Software Engineer
Carnegie Mellon University

**Comment by nyz110** [comment]
ksmurchison,I am agree with you. it's test data that I copy from other demo. it is bad data. but the libical did not rejected the data ,I think it because libical parser the data and use the first DTSTART & DTEND property. and my test log result also prove that.

**Comment by ksmurchison** [comment]
If you check the parsed data with icalrestriction_check() before trying to use it, the multiple DTSTART/DTEND should get caught.

**Comment by nyz110** [comment]
I have a test as below:
//icalStr loads from ics file whoes content is equal to before content
 icalcomponent *root = icalparser_parse_string(icalStr);
 int retVal1 = icalrestriction_check(root);
 int retVal2 = icalcomponent_check_restrictions(root)
Both return value are 0 (ICAL_RESTRICTION_NONE)
struct icaltimetype dtstart = icalcomponent_get_dtstart(event);
the return dtstart value is the first DTSTART property
To avoid some bad datas, after parsing the data ,I call icalcomponent_strip_errors(event) method to strip errs
