### ISSUE TITLE
cmake check for perl libraries when executable is enough 

### ISSUE THREAD

**Issue by jku** [libical/libical#214]
CMakeLists.txt:

    # must have Perl to create the derived stuff
    find_package(Perl REQUIRED)

As I understand it, this looks for perl libraries ("libperl-dev", which are not required): only the perl executable seems to be needed for building.

I'm doing this instead in openembedded (since I know perl is there) but you may want something fancier that actually checks that the binary is available:

    set(PERL_EXECUTABLE perl)

**Comment by winterz** [comment]
good point.  I'll see what I can do.

**Comment by winterz** [comment]
according to the current CMake docs, FindPerl only looks for the perl executable while FindPerlLibs looks for the perl libs and includes.
so unless you prove otherwise, or maybe you're using an older Cmake?  I don't think this is an issue.

**Comment by winterz** [comment]
are you saying that find_package(Perl) doesn't find your perl executable?  if so, it might be that your perl executable is in a non-standard path that cmake can't find.  I could add a hint where to look in your paths

**Comment by jku** [comment]
Hmm, maybe I do need to look closer. But perl is there in /usr/bin/, definitely in path and cmake is 3.2.2 so I doubt that's the problem.

I'll take a closer look at what happens in find_package().

**Comment by jku** [comment]
aaand you are correct: OpenEmbedded cmake environment does not seem to have /usr/bin/ in $PERL_POSSIBLE_BIN_PATHS  and that has to be the real bug.

Thanks for quick reply and sorry for the trouble: this one is entirely on me for jumping in to conclusions.

**Comment by winterz** [comment]
I'd be fine with adding a hack for OpenEmbedded in the libical CMakeLists.txt. if you send me a patch. something like
if(<somehow detect openembedded>)
set(PERL_EXECUTABLE perl)
endif()

**Comment by jku** [comment]
Thanks but it's probably better to have that hack in OE... 

I've found the real problem in the meanwhile: To prevent use of host tools during build we use "CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY". Perl however is a special case in that we do want to use host perl (for cases like libical). I'll just patch the check out of CMakeLists.txt in our build (it's safe since perl is a build requirement for OE): better do that in OE than libical so if the handling of perl changes at some point it's easier to find these hacks.

Thanks anyway.
