### ISSUE TITLE
how i can update my pc opensuse 13.2?

### ISSUE THREAD

**Issue by manuelsongokuh** [libical/libical#217]
hello, i wish to test for my pc, opensuse 13.2 kde4.14.9
for testing with korganizer (kontact) and my friend ' RapFan89' did open report bug to kde team:
https://bugs.kde.org/show_bug.cgi?id=325224

that said is FIXED, so i want to try update my pc but my YAST (opensuse control center) package libical version is 1.0-5.2.2 date : 2014-10-08 it's old version, but how i can update for opensuse?

yast package libical:
libical1 - Un'implementazione dei protocolli di base iCAL

/usr/lib64/libical.so.1
/usr/lib64/libical.so.1.0.0
/usr/lib64/libicalss.so.1
/usr/lib64/libicalss.so.1.0.0
/usr/lib64/libicalvcal.so.1
/usr/lib64/libicalvcal.so.1.0.0
/usr/share/doc/packages/libical1
/usr/share/doc/packages/libical1/AUTHORS
/usr/share/doc/packages/libical1/COPYING
/usr/share/doc/packages/libical1/ChangeLog
/usr/share/doc/packages/libical1/LICENSE
/usr/share/doc/packages/libical1/NEWS
/usr/share/doc/packages/libical1/README
/usr/share/doc/packages/libical1/TEST
/usr/share/doc/packages/libical1/THANKS
/usr/share/doc/packages/libical1/TODO
16 file in totale

maybe github latest commits will release binary for opensuse? RPM or copy and paste in /usr/lib64/ and /usr/share/doc/packages/...?

**Comment by winterz** [comment]
since the new code is binary incompatible you'll need to build the library from source and the applications from source also.

**Comment by manuelsongokuh** [comment]
ok, i wish to try with from source, but i'm not sure how do i will do...?
my pc is opensuse 13.2 kde4..
