### ISSUE TITLE
install directories are difficult to configure

### ISSUE THREAD

**Issue by jku** [libical/libical#218]
I've had some problems wrestling with the cmake build system on openembedded... It's a bit difficult to get libical to install to the directories we want (and depending on situation we want quite a few different places). 

As an example, in some situations we need to install libraries to /usr/lib64/. libical build system has a variable LIB_INSTALL_DIR but this is not settable by user:

    set(LIB_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/lib${LIB_SUFFIX}" CACHE STRING "Library directory name" FORCE)

I realise LIB_SUFFIX is settable and I _could_ extract the suffix from the path I have with a bit of work... but wouldn't it be better to just let the user/distro define LIB_INSTALL_DIR (and the other install dir variables)? Or better yet support what seem to be some sort of standards: CMAKE_INSTALL_LIBDIR, CMAKE_INSTALL_BINDIR, etc.

**Comment by winterz** [comment]
which branch are you looking at?
in master we do follow CMAKE_INSTALL_LIBDIR, CMAKE_INSTALL_INCLUDEDIR, etc.

we follow the variables provided by the GNUInstallDirs CMake module

**Comment by jku** [comment]
Sorry, forgot to mention that: this is last release so version 1.0.1. I'll see about backporting master fixes, thanks for the pointer.

Not sure about your policy on when to close issues (fix in master or released) so I'll leave that to you.

**Comment by winterz** [comment]
I'm not against backporting some of these and making a 1.0.2 release.
I'd be happy for you to do the backporting work into the 1.0 branch.
then sometime I'll make a 1.0.2 release

in the meantime, I'll close this
