### ISSUE TITLE
SIGSEGV because of strlen(NULL)

### ISSUE THREAD

**Issue by stefanu21** [libical/libical#223]
please init static char *zdir = "" (icaltz-util.c line 111) NOT static char *zdir =NULL.
if function icaltzutil_get_zone_directory(void) returns NULL. 
you take the string length from NULL in icaltimezone.c line 1734. and the behaviour is not predictable. 
In my case I got a segmentation fault....

**Comment by winterz** [comment]
which version?  the line numbers you mentioned above don't correspond to the master branch.
I can do something in the master branch to fix this, however.

**Comment by winterz** [comment]
fixed in master with commit 66096e854a837b624dec68a717edc8914f59a95a
