### ISSUE TITLE
recur and testvcal fails on Gentoo

### ISSUE THREAD

**Issue by joakim-tjernlund** [libical/libical#228]
Test project /var/tmp/portage/dev-libs/libical-2.0.0/work/libical-2.0.0_build
    Start 1: regression
1/9 Test #1: regression .......................   Passed    0.05 sec
    Start 2: recur
2/9 Test #2: recur ............................***Failed    0.00 sec
    Start 3: testmime
3/9 Test #3: testmime .........................   Passed    0.00 sec
    Start 4: testvcal
4/9 Test #4: testvcal .........................***Exception: SegFault  0.00 sec
    Start 5: process
5/9 Test #5: process ..........................   Passed    0.00 sec
    Start 6: timezones
6/9 Test #6: timezones ........................   Passed    0.21 sec
    Start 7: builtin_timezones
7/9 Test #7: builtin_timezones ................   Passed    3.89 sec
    Start 8: icalrecurtest-r
8/9 Test #8: icalrecurtest-r ..................   Passed    0.16 sec
    Start 9: icalrecurtest
9/9 Test #9: icalrecurtest ....................   Passed    0.02 sec

78% tests passed, 2 tests failed out of 9

Total Test time (real) =   4.34 sec

The following tests FAILED:
	  2 - recur (Failed)
	  4 - testvcal (SEGFAULT)
Errors while running CTest

This was tested on v2.0.0 but the same error is present in 1.0.1

There is a bug with a patch(libical-1.0.1-tests.patch take 2) at:
https://bugs.gentoo.org/show_bug.cgi?id=532296

**Comment by winterz** [comment]
you're doing an in-source build which isn't supported. but I will try your patch to see if it works.

**Comment by winterz** [comment]
committed 6feb01aba7cb3186cbf0ca825957926eb72ac675
thanks for the patch.

**Comment by joakim-tjernlund** [comment]
Thanks !
Any plans to do a new 2.0.1 release soon?
