### ISSUE TITLE
icaltimetype does not store timezone information

### ISSUE THREAD

**Issue by stlaz** [libical/libical#229]
While testing the code for my project, I noticed that no matter how icaltimetype structures are created, they do not store the timezone information about their contents. Therefore, the structure usually stores the time it is passed with the given offset but does not store the timezone information, which naturally means that the information stored within the given icaltimetype structure differs from what it should really represent.

Is there a reason why icaltimezone_convert_time does not add this information to the converted structure?

**Comment by stlaz** [comment]
Found out icaltime_convert_to_zone has to be called with the same zone on the object from icaltime_from_timet_with_zone (or possibly all the functions that behave similarly to this one). This seems rather puzzling and non-intuitive.

Could you please at least fix the documentation here so that it actually describes what's happening here?

> If the zone is not specified (NULL zone param) the time is taken to be floating, that is, valid in any timezone. Note that, in addition to the uses specified in [RFC5545], this can be used when doing simple math on couples of times.
> If the zone is specified (UTC or otherwise), it's stored in the object and it's used as the native timezone for this object.
> This means that the caller can convert this time to a different target timezone with no need to store the source timezone.

If I understand it well, the docstring here contradicts itself by saying the zone is stored if specified, yet it's not stored and the time can be converted to any zone. Does this function return 'floating' time all the time, then?

**Comment by coolmast** [comment]
I had a similar issue where the TZID is not a property of DTSTART but a parameter in the vevent. I patched my version of libical to workaround this issue. As this solves at least some timezone-related problems for me I suggest merging this into libical. Maybe this also fixes other timezone related problems.

https://pastebin.com/eFA8Zp1J

Example which gets fixed by the patch:

```
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
DTSTART:20180312T000000
DTEND:20180314T000000
SUMMARY:Some Text
TZID:Europe/Berlin
END:VEVENT
END:VCALENDAR
```

**Comment by ksmurchison** [comment]
What software generates VEVENT with a TZID property?  As far as I can tell, that it not valid iCalendar.

**Comment by coolmast** [comment]
That's our corporate holiday planning tool, i.e. closed software. Unfortunately I have no influence on the output of that system. So there was no other way than patching libical to cope with this.

**Comment by doughsay** [comment]
It's rather confusing, but according to RFC5545 (as far as I can tell), there are two valid uses of `TZID`.  One is as a "property" of a `VTIMEZONE` component, and one is as a "parameter" of a time property, like `DTSTART` or `DTEND`.

So the above usage of `TZID` inside a `VEVENT` component is indeed invalid.  A correct usage would look something like this:

```
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20180312T000000
DTEND;TZID=Europe/Berlin:20180314T000000
SUMMARY:Some Text
END:VEVENT
END:VCALENDAR
```

reference: https://tools.ietf.org/html/rfc5545#section-3.2.19

**Comment by winterz** [comment]
can I close this?

**Comment by dgl72** [comment]
icaltime_from_timet_with_zone still doesnt save the timezone in returned icaltime object. What is the right way to achieve that?
