### ISSUE TITLE
icaltime_from_timet_with_zone doesn't set the correct timezone in the returned icaltimetype

### ISSUE THREAD

**Issue by nixomose** [libical/libical#234]
From what I understand, when you have an icaltimetype, it has the values in the year/month/day/etc fields with the attached zone field applied. So if it zone says utc, the values are in utc time. If the zone is set to new york, then the values will show the local new york time.

So I made this example....

```
const char *line = "America/New_York";
icaltimezone *local_timezone = icaltimezone_get_builtin_timezone(line);
const time_t tt_now = time(NULL);
icaltimetype ic_now = icaltime_from_timet_with_zone(tt_now, 0, local_timezone);
```

ic_now will have my localtime, it was say 14:04 for 2pm local time, but the zone field will be set to NULL. 
This becomes a problem when I call icaltime_compare.
It will notice that the timezones are different, and will adjust them both to UTC for the comparison, but since the zone is zero for my local time, it thinks it is in utc time and doesn't adjust anything, and then the comparison fails, if the times really are the same.

if I shove in the correct timezone after I call icaltime_from_timet_with_zone, it works.
    ic_now.zone = local_timezone;

Should i be doing that though?  Am I missing something?

**Comment by ksmurchison** [comment]
Isn't this the same issue as https://github.com/libical/libical/issues/229 ?

**Comment by nixomose** [comment]
Does sound like it.

**Comment by winterz** [comment]
closing this as a dupe to #229
