### ISSUE TITLE
Libical Source code Built on Windows 64-bit machine

### ISSUE THREAD

**Issue by chitrac** [libical/libical#236]
Hi
I need a build version of libical 1.1.0 which has all the necessary dlls and .exes to be used in a windows built machine.
When i try to build this code , eve after fulfilling all the requirements i do not get the right build for me to use. Can you provide the same?

**Comment by winterz** [comment]
please provide a description or close this

**Comment by chitrac** [comment]
Sure
I will do that asap

On Tuesday 7 June 2016, Allen Winter <notifications@github.com> wrote:

> please provide a description or close this
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/libical/libical/issues/236#issuecomment-224266081>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARJcJok1mdxvm2BsYZ_80hDjYxtyMIOJks5qJWTrgaJpZM4IvoIB>
> .
>


-- 
Warm Regards,
Chitra Chandel

**Comment by chitrac** [comment]
Hi
Can I get the same sooner as i need it for one of my projects

**Comment by winterz** [comment]
sorry, I can't help you with that.  I could help you build from source if you show me the errors, but I don't provide binary packages or installers.
