### ISSUE TITLE
plea for help?

### ISSUE THREAD

**Issue by nixomose** [libical/libical#242]
this is not an issue with libical except that I just can't see how to either get a icaltimezone for the local timezone for windows or fabricate a icaltimezone object from the utcoffset that I was able to squeeze out of windows.

Is there something I'm missing?

In C++ in windows, there is no way that I can tell to get the olson country/city string out of the windows api.
I can get the local utc offset in minutes, but I can't see how to make an icaltimezone with that.

Somebody else must be doing this, but I can't figure it out. I looked through the examples, and test programs, but I don't see anything that does what I'm trying to do.
Any ideas?

Thanks.

**Comment by ksmurchison** [comment]
To map from a windows time zone name to an IANA time zone name, you should use CDLR:
https://github.com/unicode-org/cldr/blob/master/common/supplemental/windowsZones.xml
