### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by EvaSDK** [libical/libical#245]
Last release is almost a year old and unittests failed on my system while current master runs fine. Would it be possible to make a new release ?

**Comment by Polynomial-C** [comment]
Also seems like there are a couple of security issues reported which should be addressed with a new release as well:

https://bugs.gentoo.org/587574

**Comment by winterz** [comment]
I'm hoping to have a new release ready by the end of 2016.
As for the security issues... we know about them but that's a different issue.
