### ISSUE TITLE
Another heap-buffer-overflow in icaltime_from_string

### ISSUE THREAD

**Issue by agustinmista** [libical/libical#252]
Hello, we recently found a memory issue parsing and executing fuzzed ical file in last revision of libical (#19acf43794ad4c99f7e6687cb39424a82b737828).
We tested this issue on Ubuntu 14.04 but other configurations could be affected.
Technical details about the issue are:

```
==8764==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60400000bcb3 at pc 0x7ffff7b187ce bp 0x7fffffff8230 sp 0x7fffffff8228
READ of size 1 at 0x60400000bcb3 thread T0
```

gdb backtrace is as follows:

```
#0  0x00007ffff61cfc37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff61d3028 in __GI_abort () at abort.c:89
#2  0x00000000004b12b6 in __sanitizer::Abort() ()
#3  0x00000000004a1f97 in __asan::AsanDie() ()
#4  0x00000000004a89cf in __sanitizer::Die() ()
#5  0x00000000004a062b in __asan::ScopedInErrorReport::~ScopedInErrorReport() ()
#6  0x00000000004a0171 in __asan_report_error ()
#7  0x00000000004a0db7 in __asan_report_load1 ()
#8  0x00007ffff7b187ce in icaltime_from_string (str=<optimized out>)
    at /home/agustin/Code/libical/src/libical/icaltime.c:448
#9  0x00007ffff7b4e730 in icalperiodtype_from_string (str=<optimized out>)
    at /home/agustin/Code/libical/src/libical/icalperiod.c:68
#10 0x00007ffff7b57a32 in icalvalue_new_from_string_with_error (kind=<optimized out>, 
    str=<optimized out>, error=<optimized out>)
    at /home/agustin/Code/libical/src/libical/icalvalue.c:682
#11 0x00007ffff7b548db in icalvalue_new_from_string (kind=ICAL_PERIOD_VALUE, 
    str=0x60400000bcd0 "18640509T07014\"/18644509T173816M")
    at /home/agustin/Code/libical/src/libical/icalvalue.c:756
#12 0x00007ffff7ad080a in icalparser_add_line (parser=<optimized out>, line=<optimized out>)
    at /home/agustin/Code/libical/src/libical/icalparser.c:1147
#13 0x00000000004b8c3f in main (argc=2, argv=0x7fffffffdf08)
    at /home/agustin/Code/libical/src/test/icaltestparser.c:104
```

This issue was found using QuickFuzz, the file to reproduce it is [attached](https://github.com/libical/libical/files/627377/heap-buffer-overflow2.ical.txt).
Regards.

**Comment by ksmurchison** [comment]
This appears to be a duplicate of https://github.com/libical/libical/issues/251

**Comment by agustinmista** [comment]
Sorry for the duplicated issue, I've opened it since the attached file triggers a slightly different callstack. Feel free to delete it if you consider it's caused by the same bug.

**Comment by ksmurchison** [comment]
Fixed in https://github.com/libical/libical/issues/251

**Comment by mejo-** [comment]
I'm trying to triage the various reported security vulnerabilities (memory leaks, out of bounds, ...) against libical.

I can verify that the current git master (29cd90c21b487b5b4335059ed1a8bf7e5822a170) has this bug fixed. But other than stated by @ksmurchison it is not the same as #251. Applying only 38757ab, 04d8474 and 830d953 to 'libical' '1.0' or '0.48' doesn't fix this particular bug.

I'll do further investigation to find the responsible commit. If you have an assumption, please let me know.
