### ISSUE TITLE
libical-glib: fix warnings "Value descriptions for ICalXXX are missing in source code comment block."

### ISSUE THREAD

**Issue by winterz** [libical/libical#260]
what is causing these warning messages and can we quiet them?

**Comment by winterz** [comment]
:0: warning: Value descriptions for ICalParameterKind are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterAction are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterCutype are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterEnable are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterEncoding are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterFbtype are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterLocal are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterPartstat are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterRange are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterRelated are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterReltype are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterRequired are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterRole are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterRsvp are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterScheduleagent are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterScheduleforcesend are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterStayinformed are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterSubstate are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterValue are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterXliccomparetype are missing in source code comment block.
:0: warning: Value descriptions for ICalParameterXlicerrortype are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyKind are missing in source code comment block.
:0: warning: Value descriptions for ICalValueKind are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyAction are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyBusytype are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyCarlevel are missing in source code comment block.
:0: warning: Value descriptions for ICalProperty_Class are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyCmd are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyMethod are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyPollcompletion are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyPollmode are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyQuerylevel are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyStatus are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyTaskmode are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyTransp are missing in source code comment block.
:0: warning: Value descriptions for ICalPropertyXlicclass are missing in source code comment block.
:0: warning: Value descriptions for ICalComponentKind are missing in source code comment block.

... and so on and on...

**Comment by mcrha** [comment]
They mean there is no user documentation for the respective enums in the source code, thus the gtk-doc cannot link to them for a detailed description what they mean. There are a lot of enums and, I'm afraid, most of them would be commented like:
```c
/** ICalParameterValue:
@I_CAL_VALUE_X: custom value
@I_CAL_VALUE_BINARY: binary value
...
Parameter value type.
```

which are not useful for the documentation, because they just repeat the name of the enum in the description.

I usually ignore the gtk-doc warnings unless they end up on the `stderr` (these do not). They sometimes show valid claims, like typos in the introspection annotations, parameter name mismatch and similar, but the gtk-doc is generated from the .xml files, thus at least the argument name always matches.

If you think it would worth to fill these regardless, then I can look on it. Just let me know.

**Comment by winterz** [comment]
Ok, I agree we don't need to worry about those "value description" warnings.

what about warnings like:
```
i-cal-array.c:160: Warning: ICalGLib: invalid "scope" annotation: only valid on callback parameters
i-cal-component.c:1602: Warning: ICalGLib: invalid "closure" annotation: only valid on callback parameters
i-cal-component.c:1635: Warning: ICalGLib: invalid "closure" annotation: only valid on callback parameters
i-cal-mime.c:20: Warning: ICalGLib: invalid "closure" annotation: only valid on callback parameters
i-cal-parser.c:155: Warning: ICalGLib: invalid "closure" annotation: only valid on callback parameters
i-cal-parser.c:200: Warning: ICalGLib: invalid "closure" annotation: only valid on callback parameters
```
and
```
html/ICalAttach.html:176: warning: no link for: "GFunc" -> (<span class="type">GFunc</span>).
html/ICalAttach.html:218: warning: no link for: "GBytes" -> (<span class="type">GBytes</span>).
html/ICalAttach.html:347: warning: no link for: "NULL:CAPS" -> (<code class="literal">NULL</code>).
html/ICalObject.html:67: warning: no link for: "GObject" -> (<span class="type">GObject</span>).
html/ICalRecurrence.html:632: warning: no link for: "TRUE:CAPS" -> (<code class="literal">TRUE</code>).
html/ICalRecurrence.html:632: warning: no link for: "FALSE:CAPS" -> (<code class="literal">FALSE</code>).
html/ICalRecurrence.html:1072: warning: no link for: "GArray" -> (<span class="type">GArray</span>).
html/ICalTime.html:855: warning: no link for: "i-cal-object-free-global-objects" -> (<code class="function">i_cal_object_free_global_objects()</code>).
html/ICalTime.html:1242: warning: no link for: "i-cal-time-compare-tz" -> (<code class="function">i_cal_time_compare_tz()</code>).
html/ICalTimeSpan.html:151: warning: no link for: "g-object-unref" -> (<code class="function">g_object_unref()</code>).
html/ICalTimezone.html:1208: warning: no link for: "FILE:CAPS" -> (<span class="type">FILE</span>).
html/api-index-full.html:27: warning: no link for: "libical-glib-i-cal-forward-declarations" -> (i-cal-forward-declarations).
```

I just want to know which warnings I can safely ignore and which warnings might be something to fix.

**Comment by mcrha** [comment]
The first are typos, should be fixed.

The second, those coming from glib should go away when glib2 devel documentation is installed.

Those from ical/libical look like typos, worth to investigate.

**Comment by winterz** [comment]
then I will ignore "warning: Value descriptions" and "warning: no link for" warnings

can someone look at fixing th "invalid  annotation" warnings?

**Comment by mcrha** [comment]
I have `gtk-doc-1.34.0-1.fc40` and gobject-introspection-1.80.1-1.fc40, and  it does not claim about those invalid annotations. It seems [they had been added in 1.82](https://github.com/harfbuzz/harfbuzz/issues/4875#issuecomment-2376999402).

I see the other warnings.  The one about `i_cal_object_free_global_objects` is odd, the function of the question does exist and it has a developer comment in the `i-cal-object.c.in`. It can be "untagged" when the `()` is removed in the comment.

The warnings about the glib types/functions cannot be fixed, the glib moved from gtk-doc to gi-docgen, which are incompatible in this matter, thus gtk-doc cannot find those symbols any more. The symbols can be "unset" for the documentation, which I did in the https://github.com/libical/libical/pull/825 . It does not work for some parameter types, like the `FILE`, they are taken by the gtk-doc itself, not by an explicit comment in the libical-glib code.

I could not test the gobject-introspection warnings, I'll appreciate if you could give it a try.

About the enums, I noticed the enum itself can have a developer comment, describing what the enums are for, but the actual enum values cannot have defined a cometn right now, thus adding the overall enum comment only changes the gtk-doc warning into `_build/src/libical-glib/i-cal-derived-parameter.h:22: warning: Value descriptions for ICalParameterKind are missing in source code comment block.`. [This patch](https://github.com/user-attachments/files/17901757/ical.patch.txt) can mute it, but it uses "..." for the enum value comment, which is wrong for the users. The enums in here are mostly self-explanatory, with a certain pattern in their names, thus they could be extracted, but a comment like `@I_CAL_ANY_PARAMETER:  any` is as helpful as when nothing is exported.
