### ISSUE TITLE
icalderivedvalue.c needs to be fixed to use the v_attach data element and NOT v_string

### ISSUE THREAD

**Issue by winterz** [libical/libical#269]
icalderivedvalue.c needs to be fixed to use the v_attach data element and NOT v_string.  This is because any parsed property with VALUE=BINARY(jncluding ATTACH) is currently stored in v_attach.

**Comment by ksmurchison** [comment]
Fixed with https://github.com/libical/libical/commit/45d6fa8d0618cec7e32228fd9d10b948e7d18969
