### ISSUE TITLE
Remove deprecated functions

### ISSUE THREAD

**Issue by winterz** [libical/libical#271]
also remove the NO_WARN_DEPRECATED build option
note this in the ReleaseNotes.txt

**Comment by ksuther** [comment]
I started removing some deprecated methods in https://github.com/ksuther/libical/commits/remove-deprecated.

Some functions that mention being deprecated are still used in a few places, those will take a bit more effort to remove:

* `icaltime_from_timet`
* `icalcomponent_get_span`
* `icaltimezone_get_utc_offset`
* `icaltimezone_get_utc_offset_of_utc_time`

`icaltime_from_timet` could be bulk replaced with `icaltime_from_timet_with_zone` and pass in a NULL zone and the tests would still pass. There might be some places where actually using the time zone might be safer or better though.

`icalcomponent_get_span` is only used `icalclassify_find_overlaps`. Part of the implementation of `icalcomponent_get_span` could be moved into `icalclassify_find_overlaps`, but that might not be optimal.

`icaltimezone_get_utc_offset` and `icaltimezone_get_utc_offset_of_utc_time` don't appear to have any replacements.

**Comment by winterz** [comment]
let's definitely keep icaltimezone_get_utc_offset and icaltimezone_get_utc_offset_of_utc_time

icalcomponent_get_span I think we should keep as well. 

I'd like to replace icaltime_from_timet with icaltime_from_timet_with_zone. could you give that a shot?

**Comment by winterz** [comment]
fixed with commit c8a95f53eb9cc18f5ab8545afff0421200e979a1
thanks Kent

**Comment by winterz** [comment]
Kent, icaltime_from_timet() is still used in src/Net-ICal-Libical/netical_wrap.c
can you port that file to icaltime_from_timet_with_zone() ?

**Comment by ksuther** [comment]
I didn't change anything there because the entire binding is out of date. It looks like that wrapper hasn't been modified since 2001: https://sourceforge.net/p/freeassociation/code/HEAD/tree/trunk/libical/src/Net-ICal-Libical/.

**Comment by winterz** [comment]
ok then, let's close this
