### ISSUE TITLE
Add documentation for new publicly available functions

### ISSUE THREAD

**Issue by winterz** [libical/libical#275]
doxygen and libical-glib doc for
     + icalvalue_new_datetimedate (DATE or DATE-TIME)
     + icalvalue_set_datetimedate
     + icalvalue_get_datetimedate

also add doxygen tag @since 3.0 for these and also the functions with new signatures

**Comment by ksmurchison** [comment]
Probably also want to add docs for icalrecur_iterator_set_start()

**Comment by winterz** [comment]
done in 9ec819134eb43891fbb783bcdf845518cd6c0ee7
