### ISSUE TITLE
Allow icalrecur_iterator to skip ahead to avoid costly calculations for occurrences that app doesn't care about

### ISSUE THREAD

**Issue by ksmurchison** [libical/libical#280]
Add an icalrecur_iterator_next_after() or icalrecur_iterator_set_start() or some such to set the start point for occurrences that the app actually cares about.  This would be especially useful for expanding timezone data from today moving forward, or do avoid costly calculations for non-Gregorian occurrences.

**Comment by ksmurchison** [comment]
Proposed patch.  Only handles YEARLY, MONTHLY, DAILY at the moment.

[icalrecur_iterator_set_start.diff.txt](https://github.com/libical/libical/files/675631/icalrecur_iterator_set_start.diff.txt)

**Comment by ksmurchison** [comment]
New and improved patch.  Should handle ALL recurrence frequencies.  This also includes some unrelated code cleanup.

[icalrecur_iterator_set_start.diff.txt](https://github.com/libical/libical/files/679703/icalrecur_iterator_set_start.diff.txt)

**Comment by winterz** [comment]
looking really good.  you can ship it.
need to add some regression tests and add a bullet to the ReleaseNotes.txt though.

I like naming the static functions with the leading double-underscore.  We should follow that convention everywhere in the library code.

**Comment by ksmurchison** [comment]
Implemented by https://github.com/libical/libical/commit/1f78f9051328a5f7b67eda834e3480e138c8c001
