### ISSUE TITLE
doc/UsingLibical.txt example references unknown function icalparser_claim()

### ISSUE THREAD

**Issue by jnikula** [libical/libical#285]
Getting started is kind of annoying when you can't even build the examples. :(

**Comment by winterz** [comment]
We should think about removing the UsingLibical.txt.  Nobody maintains it -- for a long time now.
there is source code that should compile under the examples/ directory.

**Comment by winterz** [comment]
I'm closing this one in favor of a more general "let's clean UsingLibical.txt" . see #293
