### ISSUE TITLE
make uninstall doesn't exist ?

### ISSUE THREAD

**Issue by GMLudo** [libical/libical#290]
Hi,

In the master branch, it doesn't seem possible to launch **make uninstall**.
Do you have another command, or it's missing ?

Thanks for your answer.

**Comment by winterz** [comment]
you didn't miss anything.  we don't have a make uninstall target at this time.
after running 'make install' you should see a file manifest in the build dir called install_manifest (or somesuch).  at least that file shows you what's been installed and where.

**Comment by winterz** [comment]
solved with commit 1c10ad23a4b2f59127cfd372e90c03d4abaee4fa
once you 'make install' you can now undo that with 'make uninstall'

**Comment by GMLudo** [comment]
Thank you :-)
