### ISSUE TITLE
icalrecur_iterator_set_start fails with BYMONTHDAY recurrence rule

### ISSUE THREAD

**Issue by ksuther** [libical/libical#291]
This RRULE will fail when using `icalrecur_iterator_set_start`:

`RRULE:FREQ=MONTHLY;INTERVAL=12;BYMONTHDAY=31`

The first time returned by the iterator is incorrect, then subsequent calls to `icalrecur_iterator_next` will hang in `next_yearday` (https://github.com/libical/libical/blob/master/src/libical/icalrecur.c#L2753). `next_period` never increments `impl->days_index` to be larger than `ICAL_YEARDAYS_MASK_SIZE` and gets stuck. If I change the comparison to `<=` instead of `<` then it works, but I don't know if that's actually correct or just exposing problems elsewhere.

Attached is a patch for regression.c that shows the failure.

@ksmurchison, any suggestions? Am I simply asking too much of `icalrecur_iterator_set_start`?

[icalrecur_iterator_set_start_failure.txt](https://github.com/libical/libical/files/866105/icalrecur_iterator_set_start_failure.txt)

**Comment by ksmurchison** [comment]
So, does this RRULE work correctly if you don't use icalrecur_iterator_set_start()?  Not having DTSTART match the RRULE can give undefined results (as per RFC 5545), and this may be one of those cases.

Is your library compiled with ICU4C?  I'm just wondering if its broken in 1 code path or both.

**Comment by ksuther** [comment]
Yes, it works fine without it. I wasn't entirely sure if the start date had to match the rule, if that's the case it'd be nice to say that in the header to make it unambiguous.

I'm testing with ICU disabled.

**Comment by ksmurchison** [comment]
Just to clarify, if you don't use set_start(), does the first value provided by iterator_next() give you 20000331 or 2000330?  And I assume that all subsequent values are 20xx0331?

My intention when implementing set_start() was that you can give it *any* start point and it will do the right thing.  I will look into this.

My point above was about the DTSTART that you feed iterator_new().  RFC 5545 states:

The "DTSTART" property
      defines the first instance in the recurrence set.  The "DTSTART"
      property value SHOULD match the pattern of the recurrence rule, if
      specified.  The recurrence set generated with a "DTSTART" property
      value that doesn't match the pattern of the rule is undefined.

In the example you provided 2000330 doesn't match the pattern.  The current recurrence code might do the right thing, but I can't guarantee it.

**Comment by ksuther** [comment]
Sorry, I misunderstood. Yes, iterator_next gives 20000331, which I would expect. Ever since I've used libical it has done the right thing (returned the first valid date matching the rule) with mismatched DTSTART/RRULE pairings.

**Comment by winterz** [comment]
Ken, Kent,
Is this something we need to fix or not?

**Comment by ksmurchison** [comment]
I should fix it but won't have time this month due to travel and an upcoming a job change. 

--
Kenneth Murchison
Principal Systems Software Engineer
Carnegie Mellon University

**Comment by minichma** [comment]
@winterz, @ksmurchison : I absolutely agree that this should be fixed. No library (at least not a great one like libical) should ever hang due to bad user input. As DTSTART (just as any other part of a VCALENDAR) could very well be passed in from end users, this bug can impose severe stability and/or security issues.

Our application is very resource-constrained, and using icalrecur_iterator_set_start would help us in increasing efficiency, once this is fixed.

**Comment by minichma** [comment]
It seems, that the line https://github.com/libical/libical/blob/3d96ee3a3b6649febaefbfed952fea720b98e686/src/libical/icalrecur.c#L2968-L2970 should look something like this:
`increment_monthday(impl, -start.day+1);`

Otherwise the value is bumped to somewhere around the last day of this month rather than the first day of next month. In a very quick test this fixes the problem.

However, probably additional checks should be added that run during actual iteration, that detect such inconsistencies and abort with an error rather than iterating forever or returning incorrect values.

**Comment by winterz** [comment]
right.
whatever you can do to help out here would be much appreciated.

**Comment by minichma** [comment]
I'll try to find some time and propose a PR during the next days.

**Comment by minichma** [comment]
Hmm, I found another case that seems to be more challenging.

Rule: `FREQ=MONTHLY;INTERVAL=12;BYMONTHDAY=29`
DTSTART: `20000229`
set iterator start to `20170122T000000`

yields following results:
`20170301, 20180329, 20190329, ...` instead of
`20200229, 20240229, 20280229, ...`

**Comment by ksmurchison** [comment]
I'm looking into this.

**Comment by minichma** [comment]
Great, thanks!

**Comment by ksmurchison** [comment]
Latest commit should fix the issue.  Reopen issue if otherwise

**Comment by ksuther** [comment]
I found a regression: https://github.com/ksuther/libical/commit/7956fb26885180eabcd48005cbc3365ad0bb5de0

Iterating an `icaltimetype` where `is_date = 1` is yielding times where `is_date = 0`.

This does fix the original problem though!

**Comment by ksmurchison** [comment]
The is_date problem should be fixed with this:
https://github.com/libical/libical/commit/81ee43afff6c03cbda7493ede4388e4880dbdfeb

**Comment by ksuther** [comment]
Thanks, that worked. I submitted a PR to add the regression test as well.
