### ISSUE TITLE
is_utc is 0 but zone is NULL / no builtin timezones available

### ISSUE THREAD

**Issue by tikitu** [libical/libical#294]
Hi folks,

I have what might be 2 problems or might be 1 problem showing 2 faces.

I'm using `icalparser_parse_string` and getting out `icaltimetype` values that seem internally inconsistent: they have `is_utc` set to 0 (and `icaltime_is_utc` agrees they're not UTC) but their `zone` field is NULL. I suppose that might indicate a floating local-time value (?) but in this case the string gives an explicit TZID. (The string is included below; I'm seeing this with the DTSTART values.)

I guess this might be another #229, but I'm hoping instead it's some install step I'm not handling right. I suspect I might be to blame because I also get no builtin timezones reported by `icaltimezone_get_builtin_timezones` and `icaltimezone_get_builtin_timezone` reports NULL for "Europe/Amsterdam" (the location in the original file).

I'm finding this behaviour in the iOS simulator, after building `libical` with the script in 
  https://github.com/libical/XbICalendar/blob/master/libical/scripts/build.sh
There are all sorts of iOS-specific reasons this might be going wrong, but to narrow those down I would need a better understanding of how the compiled `libical.a` interacts with `zones.tab`, the zoneinfo `.ics` files, and whatever timezone info the platform supplies. (The script compiles `libical.a` with `-DUSE_BUILTIN_TZDATA=true` but beyond that I'm in the dark.) If someone could give me a general overview I would be very grateful: does `libical.a` need access to any of those files, or are they folded into the `.a` during the build process? If it needs them, how does it find them when it's linked into an executable? (As you can probably tell, I'm new to the world of libraries and linking.)

Here's the ics file I'm parsing: 

    BEGIN:VCALENDAR
    VERSION:2.0
    PRODID:Minddistrict ITH
    BEGIN:VTODO
    SUMMARY:First
    DTSTAMP;VALUE=DATE-TIME:20151029T090000Z
    DTSTART;TZID=Europe/Amsterdam;VALUE=DATE-TIME:20170101T120000
    RRULE:FREQ=DAILY;INTERVAL=2
    UID:p.2@mobile2.dev.minddistrict.com
    END:VTODO
    BEGIN:VTODO
    SUMMARY:Second
    DTSTAMP;VALUE=DATE-TIME:20151029T090000Z
    DTSTART;TZID=Europe/Amsterdam;VALUE=DATE-TIME:20170102T120000
    RRULE:FREQ=DAILY;INTERVAL=2
    UID:p.3@mobile2.dev.minddistrict.com
    END:VTODO
    END:VCALENDAR

**Comment by tikitu** [comment]
The next European DST transition is coming up, so I investigated this some more: besides some simple errors because I wasn't retaining C strings properly, this comes down to a perhaps surprising feature of `icalproperty_get_dtstart`: if the file specifies a non-UTC timezone from the builtin timezones list, the `icaltimetype` struct returned by `icalproperty_get_dtstart` *does not* have this timezone applied. (I suspect the same is also true if the `DTSTART` has a `TZID` that's defines as a `VTIMEZONE` in the same file, but I'm not 100% sure I covered all my bases there.)

I'm guessing this is as intended, and that implementations that want to cover all timezone-related complications should look up a `TZID` (if one is given) both in the builtins and in component itself.

(I'm not the only one to be confused by this: https://github.com/libical/libical/blob/master/scripts/mkderivedproperties.pl#L304 does the builtin-timezone lookup by hand but only for the `EXDATE` property, with puzzled comments about why this should be necessary.)

**Comment by tikitu** [comment]
For posterity: as far as I can see it's necessary to check explicitly if the property has a `TZID` (and if so look up the corresponding timezone by hand): I don't see any way to tell from the `icaltimetype` value whether it was intended as floating-time or not (assuming `is_utc` is not set, of course).

**Comment by ksuther** [comment]
In the current release of libical, a floating time is if `zone` is NULL, `is_utc` is 0 and `is_date` is 0. In master `is_utc` has been removed, so if you're using master (what will be 3.0) then check if `zone` is NULL and `is_date` is 0.

Regarding the built-in tzdata: Use `-DUSE_BUILTIN_TZDATA=0` and it should pull from the iOS zone info. This is our cmake command for Mac/iOS: `cmake ../.. -DICAL_GLIB=false -DUSE_BUILTIN_TZDATA=0 -DICAL_ALLOW_EMPTY_PROPERTIES=1 -DCMAKE_DISABLE_FIND_PACKAGE_ICU=True`

**Comment by tikitu** [comment]
@ksuther Thanks for the clarification. I think I need a quick sanity-check, if you didn't mind.

What I'm seeing is that given e.g. `DTSTART;TZID=Europe/Amsterdam;VALUE=DATE-TIME:20170101T120000`, `dtStart` in the following (Swift) code is reported as floating (`zone` is NULL, `is_date` and `is_utc` both 0):

    let component = icalcomponent_get_first_component(root, ICAL_VTODO_COMPONENT)
    let dtStartProperty = icalcomponent_get_first_property(component, ICAL_DTSTART_PROPERTY)!
    let dtStart = icalproperty_get_dtstart(dtStartProperty)

I can fix that by explicitly adding the timezone:

    var mutableDTStart = icalproperty_get_dtstart(dtStartProperty)
    let zone = icaltimezone_get_builtin_timezone(icalparameter_get_tzid(tzidParam))
    icaltime_set_timezone(&mutableDTStart, zone)

From your reply though I wonder if this is not intended to be necessary: if not I would be happy to open a new issue and put together a PR with a test confirming the issue (against `master`: everything I've done so far is pre-3.0), and perhaps even attempt a fix (modeled on https://github.com/libical/libical/blob/master/scripts/mkderivedproperties.pl#L304 ).

(Just to complicate the picture further, when I use your cmake command I get crashes in icaltimezone.c, apparently caused by an uninitialised timezone struct: what works for me is to leave out `-DUSE_BUILTIN_TZDATA=0` but to call `icaltimezone_set_builtin_tzdata(0)` before parsing. I hope this is unrelated to what I describe above, but I can't be sure.)

**Comment by tikitu** [comment]
That's closer! (I hadn't found that function, thanks!) But still not *quite* working for me. I think the culprit is this line: https://github.com/libical/libical/blob/master/src/libical/icalcomponent.c#L1439 (or rather, a couple of lines missing immediately following it).

I get NULL from looking up `Europe/Amsterdam` with `icaltimezone_get_builtin_timezone_from_tzid` but I *do* get a (correct) response from `icaltimezone_get_builtin_timezone`, which is documented as expecting an Olson city name, while I see code in `..._from_tzid` which checks the TZID has a non-Olson prefix: https://github.com/libical/libical/blob/master/src/libical/icaltimezone.c#L1423 So I think to get the behaviour you describe we'd need another fallback.


This seems specific enough that I could work up a test case (and perhaps improve the documentation a smidgen in the process). I'll open an issue once I have something.

Thanks for your help!

**Comment by winterz** [comment]
I have been looking at what the heck those #if 0 and #if 1 blocks in icaltimezone_get_builtin_timezone_from_tzid() are all about.  they look wrong to me.

if you reverse those #if blocks I bet things work better.  let me know

**Comment by tikitu** [comment]
Pretty sure that's not the problem, because of https://github.com/libical/libical/blob/master/src/libical/icaltimezone.c#L1423 (which, unless I'm misreading completely, is not in any of the #if blocks). Looks to me like the intention here is that `icaltimezone_get_builtin_timezone_from_tzid()` works with what you might call "full" TZIDs (requiring the prefix), while `icaltimezone_get_builtin_timezone()` works with Olson names (no prefix).

(Both also have special cases for "UTC" and "GMT", just for the sake of completeness.)

**Comment by winterz** [comment]
you may need to call set_tzid_prefix("/citadel.org/") at the top of your program.

**Comment by winterz** [comment]
oh, and we can't write correctly into

 static const char *ical_tzid_prefix = "/freeassociation.sourceforge.net/";

that's a crash.

man, this is bad.  how did we not notice this so far?
I can take a closer look sometime soon unless someone beats me to it.

**Comment by winterz** [comment]
please git pull and try again
I don't think you need to call set_tzid_prefix("/citadel.org/")  any longer.
