### ISSUE TITLE
Mozilla Public License v1.0 Link is dead in ReadMe.* files.

### ISSUE THREAD

**Issue by snelsen** [libical/libical#297]
As the title states, the link to the MPL v1.0 license in the various ReadMe files is dead.  Is this still the official Mozilla license option, or is a later one the correct one?  While I'm at it, is the LGPL v2.1 license option also still the correct one?  Thanks.

**Comment by winterz** [comment]
for MPL we should definitely fix the url.  I think we should move to MPL 2.0 at some point
for LGPL, v2.1 is correct.

**Comment by winterz** [comment]
and all the source files have the wrong URL as well...
also we should add a LICENSE.MPL.txt and a LICENSE.LGPL.txt

**Comment by winterz** [comment]
Ideally we need each source file to contain the official license header for both LGPL and MPL, not simply links to the licenses

**Comment by ericbusboom** [comment]
Hi Allen, thanks for tracking me down and asking. I support the change, as long as MPL 2.0 has similar rules for commercial use as MPL 1.0, which, as I understand it, it does. There seems to be quite a few commercial users of libical.

**Comment by winterz** [comment]
fixed i commit 878f1ea29a9d8999979c9acbf3f6a6b2f7132974
