### ISSUE TITLE
icalrecur_iterator doesn't check DST gaps

### ISSUE THREAD

**Issue by rsto** [libical/libical#318]
The icalrecur iterator includes in-existent times that occur due to DST gaps.

RFC 5545, section [3.3.10](https://tools.ietf.org/html/rfc5545#section-3.3.10) states

      Recurrence rules may generate recurrence instances with an invalid
      date (e.g., February 30) or nonexistent local time (e.g., 1:30 AM
      on a day where the local time is moved forward by an hour at 1:00
      AM).  Such recurrence instances MUST be ignored and MUST NOT be
      counted as part of the recurrence set.

But in my local setup my test shows icalrecur_iterator to only ignore in-existent dates, not times:

    Expanding FREQ=MONTHLY;COUNT=3 from 20170131T010000 in timezone Europe/Vienna
    20170131T010000
    20170331T010000
    20170531T010000

    Expanding FREQ=DAILY;COUNT=3 from 20170325T023000 in timezone Europe/Vienna
    20170325T023000
    20170326T023000
    20170327T023000

    Expanding FREQ=HOURLY;COUNT=3 from 20170326T013000 in timezone Europe/Vienna
    20170326T013000
    20170326T023000
    20170326T033000

The first example demonstrates how icalrecur_iterator correctly ignores in-existent dates February 31, 2017 and April 31, 2017.

The next two examples demonstrate how icalrecur_iterator incorrectly produces recurrence instances for the in-existent time March 26, 2017 at 2:30am in Europe/Vienna (there's a DST gap between 2am and 3am on that day in that timezone).

I haven't looked at how to fix this, yet. The code to produce the examples in this issue is located at https://gist.github.com/rsto/70ddbc54dec272a7365205a89b072f63

**Comment by winterz** [comment]
please indicate which libical version you are using.

**Comment by rsto** [comment]
Sorry, I'm at https://github.com/libical/libical/commit/29cd90c21b487b5b4335059ed1a8bf7e5822a170 with a few commits on top at our custom [cyruslibs](https://github.com/cyrusimap/libical/tree/cbd458b40baf0de85b95990ceadea46ebfba552b) fork for the Cyrus IMAP project. It's the one @ksmurchison and I are using.

With latest libical master I even get a segfault. I'm building with

      -DUSE_BUILTIN_TZDATA=true \
      -DCMAKE_SKIP_RPATH=ON \
      -DICAL_ALLOW_EMPTY_PROPERTIES=true

Probably the builtin tzdata is causing an issue, I'll investigate what's up with that.

**Comment by neilj** [comment]
@rsto The original spec is wrong; the libical behaviour is correct. See [Errata 4271](https://www.rfc-editor.org/errata_search.php?rfc=5545) that I filed.

**Comment by rsto** [comment]
Yeah, that makes sense. Thanks for the info.
