### ISSUE TITLE
icaltime_add() does not work if is_date is true [sf#32]

### ISSUE THREAD

**Issue by winterz** [libical/libical#32]
I am trying to add 1 \(one\) day to an icaltimetype structure. The code looks like this:

icaltimetype tt = \{0\};
tt.ical.is\_date = true;
tt.year	= 2008;
tt.month = 3;
tt.day	= 28;
tt.hour	= 0;
tt.minute = 0;
tt.second = 0;
tt.is\_utc = true;
tt.is\_date = true;
tt.is\_daylight = false;

struct icaldurationtype d = \{0\};
d.days = 1;
ical = icaltime\_add\(ical, d\);

The call to icaltime\_add doesn't work because icaltime\_add increases the number of seconds in tt, but icaltime\_adjust ignores the seconds value since is\_date is true. So icaltime\_add does not work if is\_date is true.

The workaround is to use this code, but it would be better if icaltime\_add worked properly:
ical.day += 1;
ical = icaltime\_normalize\(ical\);

**Comment by ksmurchison** [comment]
This appears to work fine in master.  I don't now if/when this was fixed, but ical_normalize() is just a wrapper around ical_adjust() with zeroed values, and the ical_adjust() logic looks sane for is_date.

**Comment by winterz** [comment]
closing
