### ISSUE TITLE
icalcomponent_foreach_recurrence omits first occurrence if DTSTART doesn't confirm to RRULE.

### ISSUE THREAD

**Issue by minichma** [libical/libical#325]
If the DTSTART in a VEVENT doesn't conform to the contained RRULE, icalcomponent_foreach_recurrence might omit the first recurrence instance.

I know, that this case is specified as undefined by the RFC, but in real life DTSTART often is a value provided by end users and might not fully conform to the RFC in this case. We could use libraries to sanitize such values but then we need libraries that handle the case in a meaningful way.

The problem can be reproduced with following code:

```C
void reproduce_libical_first_recurrence_missing_callback(icalcomponent *comp, struct icaltime_span *span, void *data) {

	int* foundExpected = (int*)data;
	(*foundExpected)++;
}

void reproduce_libical_first_recurrence_missing() {

	const char* calStr =
		"BEGIN:VCALENDAR\n"
		"BEGIN:VEVENT\n"
		// 14th is not a tuesday, so it doesn't conform to the rule.
		"DTSTART;20180214T020000Z\n"
		"DURATION:PT4H\n"
		"RRULE:FREQ=WEEKLY;COUNT=2;BYDAY=TU\n"
		"END:VEVENT\n"
		"END:VCALENDAR\n";

	icalcomponent *calendar = icalparser_parse_string(calStr);
	icalcomponent *event = icalcomponent_get_first_component(calendar, ICAL_VEVENT_COMPONENT);

	struct icaltimetype t_start = icaltime_from_string("20180219T000000Z");
	struct icaltimetype t_end = icaltime_from_string("20180221T000000Z");

	int foundExpectedCnt = 0;
	// we expect exactly one callback, namely on tu, 20th.
	icalcomponent_foreach_recurrence(event, t_start, t_end, reproduce_libical_first_recurrence_missing_callback, &foundExpectedCnt);

	icalcomponent_free(calendar);

	if (foundExpectedCnt == 1)
		printf("ok");
	else
		printf("test failed - first recurrence instance wasn't returned.");
}
```

This seems to be similar to but distinct from #291 .

[Edit] Fixed format of DURATION property, fixed comment and removed obsolete printf - doesn't change test outcome.

**Comment by winterz** [comment]
thank you for your work.  I'll do a closer review soon; a quick scan looks great and I see no obvious reason why I can't release a 3.0.4 soon with this patch.
