### ISSUE TITLE
FindICU from CMake 3.7

### ISSUE THREAD

**Issue by winterz** [libical/libical#327]
my hand-crafted cmake/modules/FindICU.cmake isn't the best.

If we required CMake 3.7.0 or higher, then we could use the FindICU that comes with CMake.

**Comment by krop** [comment]
Sounds reasonable, CMake 3.7.0 was released in nov. 2016

**Comment by krop** [comment]
I started refreshing the ical build system.
The FindICU.cmake in the repo looks for  additional libraries: cygicuuc, cygicuuc32, cygicuin and cygicuin32. The CMake module doesn't do that.
Is this really needed ?

**Comment by winterz** [comment]
I added those to support cygwin, iirc

too bad the CMake FindICU doesn't support that.
I don't think its worth keeping our own homemad FindICU for this.
please proceed with the build system refresh.

**Comment by krop** [comment]
https://github.com/krop/libical/commits/cmake-update has some of the changes. I have a couple more planned.

About ICU, src/test/CMakeLists.txt contains if(HAVE_ICU_DANGI) but I don't see what it is in CMake's FindICU... but also not in the old one. I only find dangi mentioned in the ICU 0.51 release note.

**Comment by winterz** [comment]
yeah, some of the older icu's didn't have the dangi data for testing
maybe a better check is to look for icu version >= 0.51

**Comment by winterz** [comment]
@krop thoughts about this patch? is it ready to go?  is it ok for 3.0.5 or should add it in master only for now (for an eventual 3.1 release)

**Comment by krop** [comment]
which patch exactly? the report was about bumping the minimum version to 3.7 and get rid of the ical copy.

My branch isn't ready, mostly because of the gtkdoc hell.

**Comment by winterz** [comment]
first attempt committed into the allen/findicu branch

**Comment by winterz** [comment]
drat.  need to figure out how to make the CMake version of FindICU find the cygwin libraries: cygicuuc, cygicuuc32, cygicuin .  at the moment we won't find libicu on cygwin.

**Comment by winterz** [comment]
no, that's not the problem on Cygwin.  I see the libraries, like so in /usr/lib:
/usr/lib/libicudata.dll.a
/usr/lib/libicudata64.dll.a
/usr/lib/libicui18n.dll.a
/usr/lib/libicui18n64.dll.a
/usr/lib/libicuio.dll.a
/usr/lib/libicuio64.dll.a
/usr/lib/libicutest.dll.a
/usr/lib/libicutest64.dll.a
/usr/lib/libicutu.dll.a
/usr/lib/libicutu64.dll.a
/usr/lib/libicuuc.dll.a
/usr/lib/libicuuc64.dll.a

Maybe we'll figure this out someday.  In the meantime I plan to merge the allen/findicu branch to master.

**Comment by winterz** [comment]
commited to master in 3eeae5d03c39982c7489921b481ebf73502775d8
