### ISSUE TITLE
modulemap for Swift?

### ISSUE THREAD

**Issue by randomstrings** [libical/libical#334]
Hi, I'm trying to get a working Swift modulemap package, but I keep getting this error when I try to compile my main project which includes the modulemap package as a dependency. Does anyone have a working modulemap they can share?

```
$ swift test
ld: library not found for -llibical for architecture x86_64
```

Here's my module.modeulmap:
```
module ClibicalMac [system] {
    header "/usr/local/include/libical/ical.h"
    link "libical"
    export *
}
```

Here's my Package.swift:
```swift
import PackageDescription
let package = Package(
    name: "Clibical",
    pkgConfig: "libical"
)
```

I have `libical` installed on my system with brew (macOS 10.12), and have verified that the header and library exist and the library is x86_64.
```
$ ls /usr/local/include/libical
ical.h ...

$ lipo -info /usr/local/lib/libical.a
Non-fat file: /usr/local/lib/libical.a is architecture: x86_64
```

**Comment by winterz** [comment]
wild ass guess:
change link "libical" to link "/usr/local/lib/libical.a"

**Comment by randomstrings** [comment]
Thank you for the guess. Still get a similar error on my end. If someone does get a working modulemap for libical, that would be handy. My use case would be for calculating rrule occurrences in server-side swift on linux (where Apple's EventKit is not available).

```
ld: library not found for -l/usr/local/lib/libical.a for architecture x86_64
```

**Comment by winterz** [comment]
https://medium.com/swift-and-ios-writing/using-a-c-library-inside-a-swift-framework-d041d7b701d9

maybe you need to add /usr/local/lib to the Swift Compiler's Search Paths->Import Paths
else I'm fresh out of guesses.
