### ISSUE TITLE
icalrecurrencetype_rscale_is_supported() not consistently checked

### ISSUE THREAD

**Issue by guidedways** [libical/libical#338]
`icalrecurrencetype_rscale_is_supported()` doesn't seem to be consistently checked when accessing or freeing `icalrecurrencetype.rscale` it seems. See line 644 in `icalrecur.c` for instance, where it seems memory is being released, which could potentially be simply NULL when support for RSCALE is unavailable.

**Comment by minichma** [comment]
Doesn't seem to be an issue at least in this very case (icalrecur.c:644), since free(0) is a no-op.

**Comment by guidedways** [comment]
True - however I've some other instances where I received a coupe of EXC_BAD_ACCESS's (caught by Xcode's Address Sanitizer). Adding the extra checks in the various places RSCALE is set / retrieved fixed it.

**Comment by winterz** [comment]
I'm happy to have a patch that makes the address sanitizer happy.

**Comment by guidedways** [comment]
Thank you, that's it
