### ISSUE TITLE
Respect TZDIR environment variable

### ISSUE THREAD

**Issue by jtojnar** [libical/libical#350]
With Nix package manager, we have the timezone data in a non-standard location. It would be nice if we could override the zoneinfo location using an environment variable.

Here is the patch we currently use:

https://github.com/NixOS/nixpkgs/blob/b0f9175d03c30c1fef056679e98f0044d20fc41f/pkgs/development/libraries/libical/respect-env-tzdir.patch

This would also be useful for GNU Guix and possibly others.

`TZDIR` variable is used by other applications as well. See, for example, [`tzselect(8)`](https://linux.die.net/man/8/tzselect).

**Comment by winterz** [comment]
Not against this patch.
Do we need to reorder the list of search_paths[]?
Also I need to find a place to document this variable.

**Comment by jtojnar** [comment]
I do not think the reorder is necessary.

**Comment by winterz** [comment]
done in commit 204523a32e410dfe7bb0ba435f96cd99c1715fc4
also added a new icaltzutil_set_zone_directory() public API for setting the zoneinfo path programmatically.

should be good enough now.

**Comment by lfam** [comment]
More than 4 years have passed since this change was made but it still hasn't made it into a release. Is it possible to issue a release containing this functionality?
