### ISSUE TITLE
export icalproperty_get_datetime_with_component?

### ISSUE THREAD

**Issue by Valodim** [libical/libical#357]
Hey folks,

I want to convert a timestamp from a string to an icaltimetype in the context of a component. I had assumed `icalproperty_get_datetime_with_component` was the way to go, but that function is deliberately [not exposed](https://github.com/libical/libical/blob/a1a1a2d65a8ac9c9d8cf4b459614ee6a7a0aff27/src/libical/icalproperty_p.h#L32) in the library.

So I'm wondering, is there another right way to do this? Why isn't `icalproperty_get_datetime_with_component` exposed? I feel like I would be either missing semantics if I just converted from string without considering the component, or otherwise duplicate library functionality on the application layer if I considered the component's timezone myself.

**Comment by winterz** [comment]
good question.  I really don't know why it isn't exposed. 

could be due to the FIXME that says "this is useless until we can flag the failure"
but it seems useful to me.  this is before my time in the project.

so far I can't see any reason not to expose it.

**Comment by winterz** [comment]
see commit 323996b2d1ea358f91c9d5f1db5060e5be6a9628
will be in an upcoming 3.0.5 release
