### ISSUE TITLE
Output only recent VTIMEZONE changes

### ISSUE THREAD

**Issue by sonea-pm8** [libical/libical#371]
I tried to add a VTIMEZONE component to a VCALENDAR component, which should only contain the most recent timezone change information, because that is the only data relevant for the contained events.
I could not find a way to do this with the currently provided API, beside iterating over all the subcomponents of the VTIMEZONE and keeping only last ones for DAYLIGHT and STANDARD.

Is there a way I didn't see, or otherwise could the API be extended to support this?

**Comment by winterz** [comment]
I don't think we have a way to do this.  you'd need to iterate, like you said.
if you can hack up some code we could look at adding it to the API in a future release.

**Comment by ksmurchison** [comment]
I have code that does exactly this as part of my CalDAV/TZdist server.  I will see if I can decouple it and add it to libical.
