### ISSUE TITLE
Increase Minimum CMake Version

### ISSUE THREAD

**Issue by winterz** [libical/libical#379]
increase CMake minimum version requirement so we can use newer CMake features

at least 3.11 so we can use find_package(iconv)

**Comment by winterz** [comment]
done in 13c6a32bcb064e2e506b9fe2af1d202b61c05fc7

**Comment by RafalGoslawski** [comment]
Hi Allen,
This change complicates the build on systems that don't have CMake 3.11 available in their repositories (i.e. Ubuntu 18.04 LTS). 
Is it strictly necessary for using find_package? I am no expert on cmake, but it seems find_package was supported at least in version 3.0.2 (https://cmake.org/cmake/help/v3.0/command/find_package.html)

Now the library requires building the build system before use of the library, which is sub-optimal. The ways to do it are either curl the install script into sudo shell (not exactly secure), or maintain a copy of cmake source and it's build scripts yourself.

(BTW: We still have some systems that only have cmake 3.5.1 available from the repository.)

**Comment by winterz** [comment]
can you use the 3.0 branch?
there are some things in cmake 3.11 I'd like to have, but I'm open to discussing.

master is a long way from being released and only people developing new features should be using it.

**Comment by RafalGoslawski** [comment]
We are relying on a pull request #364 written my colleague that we currently maintain in a fork.
We hope it will get merged, so at some point we can just follow the upstream releases and don't need to maintain a fork long term.
Maybe there's a way to keep a hard dependency on cmake low, and make the new features optional?
