### ISSUE TITLE
Require LibICU

### ISSUE THREAD

**Issue by winterz** [libical/libical#392]
allow user to un-require libicu with -DLIBICAL_WITH_LIBICU=False
something like that

**Comment by arungrover** [comment]
I am facing the same problem. I don't want to link to icui18n.
Any Idea if this is being worked out?

**Comment by winterz** [comment]
not at this time.
feel free to work on it if you want.

**Comment by winterz** [comment]
From the Install.txt file:

> You can also force CMake to ignore any of the optional dependencies
> by passing the option -DCMAKE_DISABLE_FIND_PACKAGE_\<PACKAGE\>=True.
> For instance:
> to tell cmake to ignore ICU:
>   % cmake -DCMAKE_DISABLE_FIND_PACKAGE_ICU=True

Therefore I believe this issue is already done.
