### ISSUE TITLE
Build failure in 3.0 branch

### ISSUE THREAD

**Issue by ebassi** [libical/libical#406]
The 3.0 branch got a backport that uses `libical_option` in the `CMakeLists.txt` file, but the function is only defined in the master branch.

**Comment by ebassi** [comment]
`git blame` points at commit 65980e2cf935257c9eb8c895798f730ab65a9572.

**Comment by winterz** [comment]
oops.  I was too eager in my backport cherry-pick from master.
should be fixed now with commit 6cbd1c0fc8d5cd4e0af5d82d3d9929e2bd1f36ee

**Comment by ebassi** [comment]
Thanks, can confirm that the 3.0 branch now builds correctly.
