### ISSUE TITLE
db.h of the berkeley db library is not found

### ISSUE THREAD

**Issue by arvindpro** [libical/libical#409]
Hi,

I tried compiling and building libical, after successfully installing Berkeley DB library.
When I try building libical, I get this error because of an include directive to include db.h header file.

The error is "db.h not found".
And the process stops with the above error.

Yours sincerely,
Arvind.

**Comment by arvindpro** [comment]
HI 
I have something more to add here--
In the FindBDB.cmake file-
# Look for the header file.
find_path(
  BDB_INCLUDE_DIR
  NAMES db.h
  HINTS /usr/local/BerkeleyDB.6.2/include
  DOC "Include directory for the Berkeley DB library"
)

I checked and verified that db.h is indeed in the include folder shown above.

What is wrong here? Why is it not working?

Yours sincerely,
Arvind.

**Comment by winterz** [comment]
in your libical builddir you should have a file calle CMakeCache.txt
grep in there for BDB_INCLUDE_DIR and BDB_LIBRARY.
what are those values?

Also, depends on which libical you are using.  We fixed bug in git commit 49494dd6b644c8c7b3235ef067c620f982c80d67

**Comment by winterz** [comment]
no response for over 1 year => closing.
feel free to reopen if this is still an issue.
