### ISSUE TITLE
Eliminate FindGLib.cmake

### ISSUE THREAD

**Issue by winterz** [libical/libical#414]
Is there a CMake find_package for glib that will work for us so we can remove our homegrown cmake/modules/FindGLib.cmake and FindLibXML.cmake ?

If so, first determine how high we need to set cmake_minimum_required

**Comment by krop** [comment]
CMake comes with FindLibXml2.cmake. There's no module to find GLib

**Comment by winterz** [comment]
too bad
I suppose it isn't worth the trouble to replace FindLibXML.cmake only.  also depends which cmake version is needed.

**Comment by krop** [comment]
FindLibXml2 is not an issue, it's available since ages

**Comment by krop** [comment]
> FindLibXml2 is not an issue, it's available since ages

It just doesn't provide an imported target in the minimum CMake version required by libical (3.11). That requires >= 3.12

**Comment by winterz** [comment]
eh.

**Comment by winterz** [comment]
closing.  our FindGLib.cmake is just as good as any other
