### ISSUE TITLE
Problem with "RRULE {}:Error"-lines in 3.0.4 -> 3.0.7

### ISSUE THREAD

**Issue by mortlind** [libical/libical#421]
I use kontact for mail, calendar and contacts on Debian testing+unstable. When libical3 was upgraded from 3.0.4 to 3.0.7, something went wrong with calendar entries, where lines containing "RRULE {}: Error" appeared. I think I nailed it down to libical3, since if I downgrade to 3.0.4, there is no problem. 

It may, of course, be an issue with libkf5calendarcore5abi2, which depends on libical3, using libical3 wrongly. 

The real symptom does not appear in kontact, or rather the korganizer component of kontact. The error appears when my calendar, via akonadi, is trying to sync with my Radicale server. So it might be on the Radicale part, which should tolerate "RRULE {}: Error" lines in calendar entries. 

Any insights into this?

**Comment by ksmurchison** [comment]
What is the actual RRULE being sent to the client?  My guess is that its invalid, such as having both UNTIL and COUNT directives.

**Comment by mortlind** [comment]
> What is the actual RRULE being sent to the client? My guess is that its invalid, such as having both UNTIL and COUNT directives.
You mean from libkf5calendarcore5abi2 to libical3? Is this pertaining to some change between libical3-releases 3.0.4 and 3.0.7?  I do not really know how to identify this. But I can fish out a failing entry from my Radicale log, if that would be any help? Do you have other suggestions for identifying?

**Comment by ksmurchison** [comment]
I'm not familiar with libkf5calendarcore5abi2 or Radicale or kontact, but libical 3.0.6 prevents the use of both UNTIL and COUNT in an RRULE (per RFC 5545).
My guess is that the client is trying to create an invalid RRULE with libical, or the server contains an event with an invalid RRULE and libical fails to parse it.

**Comment by mortlind** [comment]
I have tried with several types of recurrence, and also with no recurrence. The error arises both with and without recurrence. (I suppose the UNTIL and COUNT attributes are related to recurrence?)

**Comment by mortlind** [comment]
I found the following bug-report, and now think that @ksmurchison is right in hinting to something wrong with libkf5calendarcore5. A bit more investigation and I will hopefully close this issue.
https://bugs.kde.org/show_bug.cgi?id=385364

**Comment by winterz** [comment]
@mortlind which it may be that your kcalendarcore is too old.
make sure your kcalendarcore has commit 595d25ddbc6838eb7ec70a71040246f4c7c5426f from 10 Dec 2019

I believe this would be version 5.66.0

**Comment by ksmurchison** [comment]
Yes, they both determine when the recurrence ends: COUNT=n dictates that the event ends after n occurrences .  UNTIL=yyyy-mm-dd dictates that the event recurs up to and including yyyy-mm-dd.
RFC5545 states that these attributes can not both be used at the same time.  If neither are present, then the event recurs forever (e.g. a birthday or a holiday)

**Comment by mortlind** [comment]
> @mortlind which it may be that your kcalendarcore is too old.
> make sure your kcalendarcore has commit 595d25ddbc6838eb7ec70a71040246f4c7c5426f from 10 Dec 2019
> 
> I believe this would be version 5.66.0

Apt shows version 4:19.08.3-2 of libkf5calendarcore5abi2. I will try to find "the other" version numbering for this.

**Comment by mortlind** [comment]
> @mortlind which it may be that your kcalendarcore is too old.
> make sure your kcalendarcore has commit 595d25ddbc6838eb7ec70a71040246f4c7c5426f from 10 Dec 2019
> 
> I believe this would be version 5.66.0

In Debian testing, I think I can trace that version  4:19.08.3-2 of kcalcore is std-ver: 4.4.1. So I guess I will wait it out. Thanks for all your comments!

**Comment by mortlind** [comment]
A relevant KDE bug report here, concluding that it is a kcalendarcore issue: https://bugs.kde.org/show_bug.cgi?id=412751
