### ISSUE TITLE
bswap_32 wrong on FreeBSD

### ISSUE THREAD

**Issue by valpackett** [libical/libical#426]
Upgrading 3.0.4 to 3.0.8 on FreeBSD:

```
ld: error: lib/libical.so.3.0.8: undefined reference to bswap_32
```

Looking at 3.0.8, this.. very nested sequence of ifdefs:

```c
#if defined(HAVE_ENDIAN_H)
#include <endian.h>
#else
#if defined(HAVE_SYS_ENDIAN_H)
#include <sys/endian.h>
#if defined(bswap32)
#define bswap_32 bswap32
#else
#define bswap_32 swap32
#endif
#endif
#endif
```

fails to consider the case where `<endian.h>` is basically just an alias to `<sys/endian.h>` which defines `bswap32` as a macro.

**Comment by winterz** [comment]
We have this already:
```#if defined(__OpenBSD__) && !defined(bswap_32)
#define bswap_32 swap32
#endif
```
I wonder if all we need is to and another BSD flavor , like so:
```#if (defined(__OpenBSD__) || defined(DankBSD)) && !defined(bswap_32)
#define bswap_32 swap32
#endif
```
or whatever pre-defined macro tells us we're using DankBSD

**Comment by myfreeweb** [comment]
Well, except it's `bswap32` on FreeBSD. That's why the `HAVE_SYS_ENDIAN_H` branch tries both `swap32` and `bswap32`!

The `defined(__OpenBSD__)` thing is silly. Maybe just make `HAVE_ENDIAN_H` and `HAVE_SYS_ENDIAN_H` not mutually exclusive:

```c
#if defined(HAVE_ENDIAN_H)
#include <endian.h>
#endif

#if defined(HAVE_SYS_ENDIAN_H)
#include <sys/endian.h>
#if defined(bswap32)
#define bswap_32 bswap32
#else
#define bswap_32 swap32
#endif
#endif
```

Or have the build system test for particular definitions, not just files..

**Comment by winterz** [comment]
yes. agreed.
I do want to support ancient C libraries and I'm afraid to break this brittle code.

for master I'd like to move to something like this https://gist.github.com/jtbr/7a43e6281e6cca353b33ee501421860c
