### ISSUE TITLE
RRULE with BYYEARDAY and BYMONTHDAY expands differently from other implementations

### ISSUE THREAD

**Issue by ksuther** [libical/libical#428]
A user encountered this RRULE in the wild:

`FREQ=MONTHLY;BYYEARDAY=-1;BYMONTHDAY=-1`

According to RFC 5545 it's invalid:

> The BYYEARDAY rule part MUST NOT be specified when the FREQ rule part is set to DAILY, WEEKLY, or MONTHLY.

However, Google Calendar and Apple Calendar both happily ignore the `BYYEARDAY` and treat it as the last day of every month. libical seems to treat it as invalid and doesn't return any recurrences.

Any opinions on changing the behavior to improve interoperability?

**Comment by ksmurchison** [comment]
Do we happen to have the PRODID for the generator of this garbage?  Just curious.

**Comment by ksuther** [comment]
Came from Google Calendar, but Google Calendar rewrites all events to its PRODID so I don't know where it originally came from. I'll update this if I'm able to find out the source.

**Comment by ksmurchison** [comment]
The PR above simply ignores BYYEARDAY if used with FREQ=MONTHLY, regardless of whether BYMONTHDAY is specified and fixes the subject issue.
The question is should FREQ=MONTHLY;BYYEARDAY=-1 still be an error?  With this PR it won't be and BYYEARDAY will be ignored.
The bigger question is should we extend the ignore behavior to all BYxxx parts that are illegal? (BYWEEKNO used with anything other than YEARLY, BYYEARDAY used with DAILY or WEEKLY, BYMONTHDAY used with WEEKLY)

**Comment by ksmurchison** [comment]
Actually, I see that I had already created a PR for this issue.  The questions above still stand

**Comment by ksmurchison** [comment]
New API to allow the application to decide how to handle invalid RRULEs in PR #445

**Comment by ksuther** [comment]
> The bigger question is should we extend the ignore behavior to all BYxxx parts that are illegal? (BYWEEKNO used with anything other than YEARLY, BYYEARDAY used with DAILY or WEEKLY, BYMONTHDAY used with WEEKLY)

Left this as a comment in #445, but duplicating it here so the context is kept together:

I haven't thought through every permutation, but since this is working around a very specific problem I'm inclined to say we have a specific set of workarounds to allow interoperability but otherwise leave things strict. That way we have exact tests and documentation for why we accept particular incorrect behavior while not inadvertently introducing our own (and other parsers then having to account for libical's quirky behavior in the future).
