### ISSUE TITLE
Docs website: icalcomponent.h page gives 404 error

### ISSUE THREAD

**Issue by mcclurgm** [libical/libical#434]
I imagine that this is related to my recent PR #431. 

When I navigate to https://libical.github.io/libical/apidocs/icalcomponent_8h.html, the resulting page is a 404 error. I followed the link from the [file list page](https://libical.github.io/libical/apidocs/files.html). I don't know how these links are generated, so I'm not sure why this is happening exactly. But I added icalcomponent.h to the generated documentation in that PR so it must be something that happened there.

**Comment by winterz** [comment]
should be fixed.
I forgot to 'git add' the new files.

**Comment by mcclurgm** [comment]
Yep, fixed. Thanks!
