### ISSUE TITLE
libical-devel mailing lists archives missing for Mai 2018 - June 2020

### ISSUE THREAD

**Issue by dilyanpalauzov** [libical/libical#443]
http://lists.infradead.org/pipermail/libical-devel/ shows no messages between April 2018 and July 2020, yet in April 2019 I sent a message over the mailing list.

**Comment by winterz** [comment]
I don't remember who set up the mailing list.. I'll do a little digging

**Comment by winterz** [comment]
oh well.
I haven't a clue on this.

**Comment by winterz** [comment]
in the meantime we switched to github discussions.

I never heard back from my nagging.
