### ISSUE TITLE
Test failures with tzdata 2020c

### ISSUE THREAD

**Issue by FRidh** [libical/libical#449]
The following tests fail with 3.0.8 and tzdata 2020c:

```
  The following tests FAILED:
          1 - regression (SEGFAULT)
         36 - recur (SEGFAULT)
         41 - timezones (Failed)
         45 - libical-glib-array (Failed)
         47 - libical-glib-component (Failed)
         56 - libical-glib-timezone (Failed)
```

**Comment by winterz** [comment]
> The following tests fail with 3.0.8 and tzdata 2020c:
> 
> ```
>   The following tests FAILED:
>           1 - regression (SEGFAULT)
>          36 - recur (SEGFAULT)
>          41 - timezones (Failed)
>          45 - libical-glib-array (Failed)
>          47 - libical-glib-component (Failed)
>          56 - libical-glib-timezone (Failed)
> ```
A similar issue (https://github.com/libical/libical/issues/454)  for the Mageia linux distro. The problem there seems to be due to TZif2 formatted files showing up in the system's zoneinfo.  Could this be the case  here as well?

**Comment by jtojnar** [comment]
Apparently the timezone dumps have switched to a "slim" format since 2020b. For now, we (NixOS) have [switched](https://github.com/NixOS/nixpkgs/pull/102946) tzdata back to the old "fat" format.

**Comment by ksmurchison** [comment]
Duplicate of #454

**Comment by ksmurchison** [comment]
Should be fixed by https://github.com/libical/libical/commit/c7e767bfe1d218aaf845686f9811195cecc7be2a
