### ISSUE TITLE
Remove bundled Olson database

### ISSUE THREAD

**Issue by dilyanpalauzov** [libical/libical#450]
Nowadays there are different ways to obtain timezone information on a running system:
* using the operating system’s knowledge about timezones, e.g. Windows, Linux and Android have such knowledge
* using International Components of Unicode, which transfers its TZ knowledge e.g. to nodejs
* using libical with bundled TZ data
* using pytz
* using ica4j, as does DavX5
* using RFC 7808 Time Zone Data Distribution Service (and RFC 7809 CalDAV: Time Zones by Reference)
* private copy of IANA TZ, as anything else is not reliable to contain current data

As result an operating system carries many definitions of the time zones, and it is likely that some of these definitions are outdated, as it is much more work to update all the definitions on many places, than one place.  Any software that uses any of the above sources can run into a situation, that it uses outdated data, the only way around this is to check all available TZ sources on the system and taking the most current one.  The last idea does not happen in practice.

libical/zoneinfo uses tzdata 2019c, which is outdated, and even if it was current, this would not help those, who have not updated libical.

To help the user, maintainer, administrator, Linux distribution, remove the bundled TZ data from libical, and the corresponding compile time option, so that the objects have to update TZ data on less places.

**Comment by winterz** [comment]
how would this work on Windows

**Comment by dilyanpalauzov** [comment]
I do not how Windows operates with TZ data, apart that they put significant efforts to update the TZ definitions, as evident from https://techcommunity.microsoft.com/t5/daylight-saving-time-time-zone/bg-p/DSTBlog.  If this cannot be achieved under Windows, then include the bundled TZ data, only on Windows.

**Comment by winterz** [comment]
what we have now:
 if Windows => -DUSE_BUILTIN_TZDATA=True always
 else => -DUSE_BUILTIN_TZDATA=False but can be enabled if desired

I'm not seeing the problem.

**Comment by dilyanpalauzov** [comment]
I use ccmake and whenever I compile it, I have to decide, if the bundled data shall be used.  If this is not up to the user, ccmake shall not show the option.

**Comment by dilyanpalauzov** [comment]
The problem is, that probably nobody, who desies to enable the option, is aware of the consequences.

**Comment by winterz** [comment]
valid complaints.
In commit 72655371c4e1d48bfdefa61b0a0de3d62cb3149b I marked some variables "Advanced" so you only see them if you toggle the advanced options in ccmake.  I also put a "Careful" on the option description. 

please take a look and let me know if this helps you.

**Comment by dilyanpalauzov** [comment]
Is there a use-case, where on Linux this option is usefull?  If not, I recommend deprecating it in some form, detect Windows at compile time with `#if defined(_WIN32) || defined(WIN32) || defined(__CYGWIN__) || defined(__MINGW32__) || defined(__BORLANDC__)` (as recommended at https://stackoverflow.com/a/1020176) and finally removing the cmake option.

I propose not saving any words, and replacing the help text
> (Careful) Build using libical's built-in timezone data, else use the system timezone data on non-Windows systems. ALWAYS true on Windows. Non-Windows users should know what they're doing if they choose not to use system provided timezone data. The libical project does not guarantee that the built-in timezone data is up-to-date.

with
> (Careful) Build using libical's built-in timezone data, else use the system timezone data on non-Windows systems. ALWAYS true on Windows. When this option is used, the bundled timezone data is eventually outdated, as the operating system updates only its own timezone definitions.  When enabled, it is the responsibility of the libical user to provide periodically accurate timezone definitions.  For these reasons enabling this option is discoraged on Linux.

and adding text in Readme.txt that at least on Windows, libical users need their own process to update the timezone definitions.

Rationale: I (used to) compile most things myself and as rule of thumb, I consider that enabling more options/features is always good.  I have enabled that options (for a while) on Linux and that help text in cmake would have probably not had changed my mind.

**Comment by dilyanpalauzov** [comment]
Removing the bundled Olson database, so that only Windows developers, that are capable to generate the database once and periodically, can use the 'bundled' feature, is a very good idea.

**Comment by winterz** [comment]
I like things as they are.
