### ISSUE TITLE
icaltzutil_fetch_timezone() generates wrong recurrence rules

### ISSUE THREAD

**Issue by kuruczgy** [libical/libical#478]
The `icaltzutil_fetch_timezone` function reads tzinfo files, and turns them into VTIMEZONE components.

The algorithm works by detecting patterns in the transitions, and turning them into recurrence rules. It unfortunately fails to detect situations where the time at which the transitions happen changes, but the date doesn't.

This is the case for `Europe/Budapest` for instance. Looking at the transitions (`zdump -V Europe/Budapest`):
```
Europe/Budapest  Sat Sep 24 22:59:59 1983 UT = Sun Sep 25 00:59:59 1983 CEST isdst=1 gmtoff=7200
Europe/Budapest  Sat Sep 24 23:00:00 1983 UT = Sun Sep 25 00:00:00 1983 CET isdst=0 gmtoff=3600
Europe/Budapest  Sun Mar 25 00:59:59 1984 UT = Sun Mar 25 01:59:59 1984 CET isdst=0 gmtoff=3600
Europe/Budapest  Sun Mar 25 01:00:00 1984 UT = Sun Mar 25 03:00:00 1984 CEST isdst=1 gmtoff=7200
Europe/Budapest  Sun Sep 30 00:59:59 1984 UT = Sun Sep 30 02:59:59 1984 CEST isdst=1 gmtoff=7200
Europe/Budapest  Sun Sep 30 01:00:00 1984 UT = Sun Sep 30 02:00:00 1984 CET isdst=0 gmtoff=3600
```
you can see that the date pattern does not change, but the time does in fact.

This causes libical to report wrong transitions times indefinitely into the future (printed with `icaltimezone_dump_changes`):
```
[...]
Europe/Budapest 28 Mar 2020     23:00:00        +0200
Europe/Budapest 25 Oct 2020      1:00:00        +0100
Europe/Budapest 27 Mar 2021     23:00:00        +0200
Europe/Budapest 31 Oct 2021      1:00:00        +0100
Europe/Budapest 26 Mar 2022     23:00:00        +0200
Europe/Budapest 30 Oct 2022      1:00:00        +0100
[...]
```
(The transitions should happen at 1:00:00 UTC, but libical reports 23:00:00 on the previous day.)

**Comment by winterz** [comment]
fixed with c7550520f4e244851e85d337a79e1ac1079b5e15
