### ISSUE TITLE
Cross-compile:  include could not find load file:  ICAL_GLIB_SRC_GENERATOR-NOTFOUND 

### ISSUE THREAD

**Issue by kanavin** [libical/libical#481]
Attempting to cross-compile, I am getting the following in do_configure():

```
| CMake Error at src/libical-glib/CMakeLists.txt:81 (include):
|   include could not find load file:
| 
|     ICAL_GLIB_SRC_GENERATOR-NOTFOUND
```
This was introduced by the following commit:
https://github.com/libical/libical/commit/1197d84b63dce179b55a6293cfd6d0523607baf1

I can't wrap my head around it. How is it supposed to work and set the native generator binary? Am I missing something?

**Comment by winterz** [comment]
do these wiki instructions help? https://github.com/libical/libical/wiki/For-the-Users:-Cross-compiling

**Comment by kanavin** [comment]
Unfortunately not. I get the same error. Can you try to do this locally please?

By the way, the instructions seem to get both the filename and the keyword wrong?
Should be IcalGlibSrcGenerator.cmake and ICAL_GLIB_SRC_GENERATOR, respectively, no?

By 'can't wrap my head', I meant specifically this snippet:
```
if(CMAKE_CROSSCOMPILING)
  # import native ical-glib-src-generator when cross-compiling
  set(IMPORT_ICAL_GLIB_SRC_GENERATOR "ICAL_GLIB_SRC_GENERATOR-NOTFOUND"
    CACHE FILEPATH
    "Path to exported ical-glib-src-generator target from native build"
  )
  include(${IMPORT_ICAL_GLIB_SRC_GENERATOR})
```
How is the above supposed to work at all, if it's forced to a bogus value?

**Comment by winterz** [comment]
@lopsided98 can you help here?

**Comment by lopsided98** [comment]
I was asked to make some changes to the naming in https://github.com/libical/libical/pull/471 and it looks like the instructions were not updated. Otherwise, those instructions should be correct. The manually specified path overrides the placeholder default value. Could you post the command you tried?

**Comment by kanavin** [comment]
-DICAL_GLIB=True -DICAL_GLIB_SRC_GENERATOR=/home/akanavin/poky/build/tmp/work/core2-64-poky-linux/libical/3.0.9-r0/recipe-sysroot-native/usr/lib/cmake/LibIcal/IcalGlibSrcGenerator.cmake

```
CMake Error at src/libical-glib/CMakeLists.txt:81 (include):
  include could not find load file:

    ICAL_GLIB_SRC_GENERATOR-NOTFOUND
```

```
$ ls -l /home/akanavin/poky/build/tmp/work/core2-64-poky-linux/libical/3.0.9-r0/recipe-sysroot-native/usr/lib/cmake/LibIcal/IcalGlibSrcGenerator.cmake
-rw-r--r-- 1 akanavin akanavin 4033 Feb 27 22:40 /home/akanavin/poky/build/tmp/work/core2-64-poky-linux/libical/3.0.9-r0/recipe-sysroot-native/usr/lib/cmake/LibIcal/IcalGlibSrcGenerator.cmake
```

Can you try those same instructions locally please? Do they really work for you? Can you tell me exactly what works?

**Comment by lopsided98** [comment]
You need to pass `-DIMPORT_ICAL_GLIB_SRC_GENERATOR` not `-DICAL_GLIB_SRC_GENERATOR`.

**Comment by kanavin** [comment]
Thanks, that works!

**Comment by winterz** [comment]
let me know if there are any changes needed on the wiki

**Comment by kanavin** [comment]
It should say 
DIMPORT_ICAL_GLIB_SRC_GENERATOR=.../cmake/LibIcal/IcalGlibSrcGenerator.cmake

**Comment by winterz** [comment]
done.

**Comment by kanavin** [comment]
Not quite:
shoulf be IcalGlibSrcGenerator.cmake

**Comment by winterz** [comment]
done, part2

**Comment by kanavin** [comment]
Thanks, looks right now.
