### ISSUE TITLE
Issue with icalrecur_iterator_set_start() and HOURLY schedules

### ISSUE THREAD

**Issue by EmielBruijntjes** [libical/libical#491]
When you use an iterator to traverse over an HOURLY schedule, and you want to start somewhere later in that schedule (using iterator_set_start()), the iterator only seems to respect the _date_-part of the supplied start-time, and not the _time_-part. For the time it still relies on the DTSTART of the original schedule, and it skips too many places. See the following example.

## Example program that demonstrates the issue
```
#include <iostream>
#include <libical/ical.h>

int main()
{
    // hourly schedule (start on 2021-03-01 at 14:20, then run every hour)
    const char *input = "BEGIN:VEVENT\nDTSTART;TZID=Europe/Amsterdam:20210301T142000\nRRULE:FREQ=HOURLY\nEND:VEVENT";
    
    // parse the component
    auto *component = icalcomponent_new_from_string(input);
    
    // get the rrule
    auto *rruleprop = icalcomponent_get_first_property(component, ICAL_RRULE_PROPERTY);
    
    // get the rrule
    auto rrule = icalproperty_get_rrule(rruleprop);

    // get the dtstart
    auto dtstart = icalcomponent_get_dtstart(component);

    // create the iterator
    auto *iter = icalrecur_iterator_new(rrule, dtstart);

    // start time for iterating (we start on 2021-03-27 at 10:00, so the next expected occurance is 2021-03-27 at 10:20)
    auto iterstart = icaltime_from_string("20210327T100000");

    std::cout << "set iterator start: " << icaltime_as_ical_string(iterstart) << std::endl;
    
    // move the iterator to the alternative start-date
    icalrecur_iterator_set_start(iter, iterstart);

    // show a number of occurences
    for (size_t i = 0; i < 1; ++i)
    {
        // get the first value from the iterator
        auto value = icalrecur_iterator_next(iter);
        
        // leap out when done    
        if (icaltime_is_null_time(value)) break;
        
        // report the value (expected: "2021-03-27 at 10:20", but we get 14:10!)
        std::cout << "got value:          " << icaltime_as_ical_string(value) << std::endl;
    }
    
    // @todo memory clean up, etc
    
    // done
    return 0;
}
```
## Compile instructions
On a Linux system, run this:
```
g++ -std=c++11 example.cpp -lical
```
Then run the program with "./a.out"
## Expected output
```
set iterator start: 20210327T100000
got value:          20210327T102000
```
I would expect the iterator to return the _first_ possible occurance _after_ the supplied time (in this case 10:20)

## Actual output
```
set iterator start: 20210327T100000
got value:          20210327T142000
```
However, it skips a number of positions, and returns the 14:20 time instead, which seems to come from the DTSTART property, which is not so much relevant here.

## Question

Is this indeed an issue, or are my expectations wrong?

**Comment by ksmurchison** [comment]
Fixed with:

https://github.com/libical/libical/commit/377d809637ba5c93e78aba30b6543c5d60d5f5ff (3.0)
https://github.com/libical/libical/commit/3f37ac8a8f5e32bd1d165e7080f5133ac7df16ee (master)
