### ISSUE TITLE
icalcomponent_get_duration doesn't handle empty DURATION and DTEND

### ISSUE THREAD

**Issue by mcclurgm** [libical/libical#493]
I'm not 100% clear on what the spec requires, but I think that this is an unhandled case.

The `icalcomponent_get_duration` function assumes that at least one of the DURATION and DTEND properties exists. See the if/else block at https://github.com/libical/libical/blob/b431861d77ad22d0890e419b03fc7226d69f65c2/src/libical/icalcomponent.c#L1502 
It only checks whether exactly one of the two properties exists, otherwise it throws a malformed metadata error, assuming that means that both exist.

By what I understand of the [spec](https://icalendar.org/iCalendar-RFC-5545/3-6-1-event-component.html), it is possible to have neither. (This is accounted for in code that uses `icalcomponent_get_dtend`.) This should be accounted for in a third case in the code, if I am reading the spec correctly.

**Comment by winterz** [comment]
I think you're correct that you can have events (like anniversary) without an end-date nor a duration.  
In that case the DTSTART would need to be a DATE (not a DATE-TIME) and we would assume a duration of 24 hours.
I suppose.

@ksuther or @ksmurchison thoughts?

**Comment by mcclurgm** [comment]
I suppose one further question is whether we want to account for this case directly in either function. Even `icalcomponent_get_dtend ` doesn’t account for when both properties are missing, it’s just the calling code that does. This puts the responsibility on all client code to check for the case when the spec requires the same behavior in all cases (I think), so it could make sense to build in to the function.

**Comment by dilyanpalauzov** [comment]
See https://github.com/libical/libical/pull/519.

**Comment by winterz** [comment]
can we close this one now?
#519 has been committed to the 3.0 and master branches

**Comment by mcclurgm** [comment]
Yes, that fixes my issue. Thanks!
