### ISSUE TITLE
Facing compilation issues while executing cmake in sles 12 for Libical v3.0.8

### ISSUE THREAD

**Issue by bremanandjk** [libical/libical#494]
We are seeing an intermitted hang while running CMake on Sles 12 platform, the hang issue is observed in Cmake V3.5 and Cmake V3.20. 

Debug Logs:

/home/waddell/cmake-3.20.1/Modules/Internal/CheckSourceCompiles.cmake(87):  message(CHECK_START Performing Test HAVE_GCC_POINTER_MEMACCESS )
   Called from: [4]     /home/waddell/cmake-3.20.1/Modules/Internal/CheckSourceCompiles.cmake
                [3]     /home/waddell/cmake-3.20.1/Modules/Internal/CheckCompilerFlag.cmake
                [2]     /home/waddell/cmake-3.20.1/Modules/CheckCCompilerFlag.cmake
                [1]     /home/brema/x1/x2/x3/2022.0.0/binaries/libical/CMakeLists.txt
-- Performing Test HAVE_GCC_POINTER_MEMACCESS
   Called from: [4]     /home/waddell/cmake-3.20.1/Modules/Internal/CheckSourceCompiles.cmake
                [3]     /home/waddell/cmake-3.20.1/Modules/Internal/CheckCompilerFlag.cmake
                [2]     /home/waddell/cmake-3.20.1/Modules/CheckCCompilerFlag.cmake
                [1]     /home/brema/x1/x2/x3/2022.0.0/binaries/libical/CMakeLists.txt
/home/waddell/cmake-3.20.1/Modules/Internal/CheckSourceCompiles.cmake(89):  try_compile(HAVE_GCC_POINTER_MEMACCESS /home/brema/x1/x2/x3/2022.0.0/binaries/libical /home/brema/x1/x2/x3/2022.0.0/binaries/libical/CMakeFiles/CMakeTmp/src.c COMPILE_DEFINITIONS -DHAVE_GCC_POINTER_MEMACCESS -Wsizeof-pointer-memaccess   CMAKE_FLAGS -DCOMPILE_DEFINITIONS:STRING=  OUTPUT_VARIABLE OUTPUT )
   Called from: [4]     /home/waddell/cmake-3.20.1/Modules/Internal/CheckSourceCompiles.cmake
                [3]     /home/waddell/cmake-3.20.1/Modules/Internal/CheckCompilerFlag.cmake
                [2]     /home/waddell/cmake-3.20.1/Modules/CheckCCompilerFlag.cmake
                [1]     /home/brema/x1/x2/x3/2022.0.0/binaries/libical/CMakeLists.txt
CMake Warning (dev) at /home/waddell/cmake-3.20.1/Modules/Internal/CheckSourceCompiles.cmake:89 (try_compile):
  Policy CMP0066 is not set: Honor per-config flags in try_compile()
  source-file signature.  Run "cmake --help-policy CMP0066" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  For compatibility with older versions of CMake, try_compile is not honoring
  caller config-specific compiler flags (e.g.  CMAKE_C_FLAGS_DEBUG) in the
  test project.
Call Stack (most recent call first):
  /home/waddell/cmake-3.20.1/Modules/Internal/CheckCompilerFlag.cmake:66 (cmake_check_source_compiles)
  /home/waddell/cmake-3.20.1/Modules/CheckCCompilerFlag.cmake:40 (cmake_check_compiler_flag)
  CMakeLists.txt:445 (check_c_compiler_flag)
This warning is for project developers.  Use -Wno-dev to suppress it.

   Called from: [4]     /home/waddell/cmake-3.20.1/Modules/Internal/CheckSourceCompiles.cmake
                [3]     /home/waddell/cmake-3.20.1/Modules/Internal/CheckCompilerFlag.cmake
                [2]     /home/waddell/cmake-3.20.1/Modules/CheckCCompilerFlag.cmake
                [1]     /home/brema/x1/x2/x3/2022.0.0/binaries/libical/CMakeLists.txt
CMake Warning (dev) at /home/waddell/cmake-3.20.1/Modules/Internal/CheckSourceCompiles.cmake:89 (try_compile):
  Policy CMP0056 is not set: Honor link flags in try_compile() source-file
  signature.  Run "cmake --help-policy CMP0056" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For compatibility with older versions of CMake, try_compile is not honoring
  caller link flags (e.g.  CMAKE_EXE_LINKER_FLAGS) in the test project.
Call Stack (most recent call first):
  /home/waddell/cmake-3.20.1/Modules/Internal/CheckCompilerFlag.cmake:66 (cmake_check_source_compiles)
  /home/waddell/cmake-3.20.1/Modules/CheckCCompilerFlag.cmake:40 (cmake_check_compiler_flag)
  CMakeLists.txt:445 (check_c_compiler_flag)
This warning is for project developers.  Use -Wno-dev to suppress it.

   Called from: [4]     /home/waddell/cmake-3.20.1/Modules/Internal/CheckSourceCompiles.cmake
                [3]     /home/waddell/cmake-3.20.1/Modules/Internal/CheckCompilerFlag.cmake
                [2]     /home/waddell/cmake-3.20.1/Modules/CheckCCompilerFlag.cmake
                [1]     /home/brema/x1/x2/x3/2022.0.0/binaries/libical/CMakeLists.txt

We have raised an issue with CMake community also https://discourse.cmake.org/t/cmake-hung-while-compiling-libical/3018 
It would be better if you could look into this case. Their suggestion is not to use CheckFunctionExists module in Cmake projext, instead use CheckSymbolExists. 

Wanted to know, whether sles12 is officially supported to built libical v3.0.8

Please let us know if there are any logs required to debug further.

**Comment by winterz** [comment]
please test pull request #496

**Comment by bremanandjk** [comment]
> please test pull request #496

Hey @winterz,
Thanks a lot for your efforts to attempt to fix this issue, It seems the issue is not only specific to identifying the signal() Api the hang happens at random another check also. (like identifying nanosleep, assert). Its issue with respect to checking any API availability in system sles 12. 

looks like the proposd change only for signal, this may not solve "the cmake hang issue with libcial build process". Since we are automating the build process, it's hanging at multiple places in each iteration. 

Even somtimes, the hang at checking library existence also, Basically we need successful libical configuration, compilation in any CI environment for sles 12 to confirm its stability.

**Comment by winterz** [comment]
closing.
I can't see what we can do here.
