### ISSUE TITLE
Support db-6

### ISSUE THREAD

**Issue by dmacks** [libical/libical#505]
Building libical-3.0.10 on OS X 10.13 against libdb-6.0.30 gives a warning:
```
/sw/build.build/libical3-shlibs-3.0.10-1/libical-3.0.10/src/libicalss/icalbdbset.c:413:34: warning: incompatible pointer types passing 'int (DB *, const DBT *, const DBT *)' (aka 'int (struct __db *, const struct __db_dbt *, const struct __db_dbt *)') to parameter of type 'int (*)(DB *, const DBT *, const DBT *, size_t *)' (aka 'int (*)(struct __db *, const struct __db_dbt *, const struct __db_dbt *, unsigned long *)') [-Wincompatible-pointer-types]
        dbp->set_bt_compare(dbp, _compare_keys);
                                 ^~~~~~~~~~~~~
```
that does not occur when building against db-5.3.28. This is a result of an API change for ```set_bt_compare()``` in db6 vs db5: https://docs.oracle.com/cd/E17276_01/html/installation/compare_func.html

Some distros have licensing concerns about db6 whereas others are trying to migrate to it as much as possible, so it might be nice to have cmake check the version and adjust the ```_compare_keys()``` signature accordingly.

**Comment by winterz** [comment]
I have a Mac here and can look at this.
do you know which homebrew recipes I need to install libdb5 and libdb6?
I'm hoping the API provides a version macro we can rely on for conditional compiling

**Comment by winterz** [comment]
indeed when I build on my Mac I see 
`/Users/allen/projects/libical/libical/src/libicalss/icalbdbset.c:413:34: warning:
      incompatible pointer types passing 'int (DB *, const DBT *, const DBT
      *)' (aka 'int (struct __db *, const struct __db_dbt *, const struct
      __db_dbt *)') to parameter of type 'int (*)(DB *, const DBT *, const
      DBT *, size_t *)' (aka 'int (*)(struct __db *, const struct __db_dbt *,
      const struct __db_dbt *, unsigned long *)')
      [-Wincompatible-pointer-types]
        dbp->set_bt_compare(dbp, _compare_keys);`

maybe I already have db-6 installed

**Comment by dmacks** [comment]
No idea about brew. I use fink, where the patch to use the updated API is:

fink/fink-distributions@d2bb3d86ef2d787ac7a4df8022b2d6e4a364e395

**Comment by winterz** [comment]
on my linux system: db.h says DB_VERSION_MAJOR 5  from 2013!  ancient. I wonder why.
from the homebrew db.h on Mac: we have DB_VERSION_MAJOR 18 from 2020

I will make the conditional compile against DB_VERSION_MAJOR>5

**Comment by winterz** [comment]
fixed in 8af29ffa5c5a228c519efbe08762ab59172fc76a

**Comment by dmacks** [comment]
Good test! On my Mac, /usr/include/db.h is from 1994 and doesn't define DB_VERSION_MAJOR at all, so clearly defaulting to old is the way to go. Per Oracle's docs, locp is supposed to be set to NULL, not just ignored. See also their sample code at https://docs.oracle.com/database/bdb181/html/gsg/CXX/btree.html

**Comment by winterz** [comment]
will fix locp
and I will check if DB_VERSION_MAJOR is defined at all

**Comment by winterz** [comment]
see 15cf1ddf5331f828adc59ac74be83c7b119f5542
