### ISSUE TITLE
The pkg-config files specify the wrong library directory

### ISSUE THREAD

**Issue by veractor** [libical/libical#508]
For instance, when the libraries are installed to `/usr/lib64`, `/usr/lib64/pkgconfig/libical.pc` and `/usr/lib64/pkgconfig/libical-glib.pc` will have the line `libdir=${exec_prefix}/lib` instead of `libdir=${exec_prefix}/lib64`. This means that if libical is installed as both 32-bit and 64-bit, dependents of this library might fail to compile if they use those files to get link flags.

Setting LIB_INSTALL_DIR in CMake did not affect those lines at all.

**Comment by winterz** [comment]
fixed in e840bbb08cc651a44044a8abc36935ca9d7a4fd4
