### ISSUE TITLE
v3.0.11 still contains FindICU module, which was removed in master

### ISSUE THREAD

**Issue by wrobelda** [libical/libical#514]
As discussed in Microsoft/vcpkg#20966, building libical statically fails. This is caused by the custom/obsolete `FindICU.cmake` module included with the sourcecode. 

The same module is provided by CMake upstream, starting with 3.7, which was released on 2017-01-13. I think it's fair to assume that everyone uses this version by now.

**Comment by winterz** [comment]
I don't want to increase the CMake version requirement in the 3.0 (stable) branch. 
I will investigate how we can solve this problem without doing so

**Comment by wrobelda** [comment]
3.7 is almost 4 years old. Realistically speaking, who would package new versions for a distribution featuring cmake older than that?

**Comment by winterz** [comment]
as a compromise, I put a copy of the official CMake3.21 FindICU into the 3.0 branch.
can you test the 3.0 branch now?  If it works I can schedule a new 3.0.x release.

**Comment by wrobelda** [comment]
> as a compromise, I put a copy of the official CMake3.21 FindICU into the 3.0 branch.
> can you test the 3.0 branch now? If it works I can schedule a new 3.0.x release.

Sorry for a late reply. The problem vcpkg had with icu is actually unrelated to your bespoke CMake module, but replacing it with a vanilla CMake one in 3.0 branch is still a nice addition. Thanks.

**Comment by winterz** [comment]
@wrobelda ok.  to recap: the libical vcpkg has been accepted and committed and seems to be working fine with icu, right?
you did find a problem with ninja when building with ICAL_GLIB if I recall?

**Comment by wrobelda** [comment]
No, I had to disable `icu` on static builds because I couldn't get it to work. I figure it's worth having it in vcpkg as is and revisit the issue later on.
And yes, I found an issue with ninja with `ICAL_GLIB` enabled. I can send a patch your way that adds that feature to vcpkg port if you want to inspect the issue on your end. I don't know much about Ninja unfortunately, so can't help much.

**Comment by winterz** [comment]
I'd be happy if you'd create new issues for these problems, please.
also note on which platforms they occur, if you can

**Comment by winterz** [comment]
https://github.com/libical/libical/issues/527 refers the ninja problem
