### ISSUE TITLE
Create i_cal_time_format

### ISSUE THREAD

**Issue by tintou** [libical/libical#521]
In GLib we have [`g_date_time_format`](https://developer-old.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format) which provides a convenient way to returned a string from a `GDateTime`, it would be great to have the same function in libical-glib (which would probably just be an adaptation of [GLib's code](https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/gdatetime.c) but using ICalTime)

**Comment by mcrha** [comment]
The idea of the libical-glib was to be roughly 1:1 with the libical, to make the transition between the two easier.

**Comment by winterz** [comment]
@mcrha does that mean you are against having the associated patch in libical?

**Comment by mcrha** [comment]
Yes, I'm against it. It would make more sense to have it in the libical and add a wrapper for it into libical-glib, but even then it means maintaining 1300+ lines of code, which is copied from glib.

A better thing would be to have `ICalTime~>GDateTime` convert function and then use the GLib format functions directly. I understand there's a problem with the timezone, but even that can be done on the client side, when the client knows what timezone it expects for its UI. All these things can be done more or less on the easily on the client side, keeping the libical for the iCalendar manipulation.

It's only my opinion.

**Comment by winterz** [comment]
@tintou I'll close this since you seem to have dropped the idea for more than 2.5 years :)
feel free to re-open if you want
