### ISSUE TITLE
Handle (optional) parameter in libical-glib generator

### ISSUE THREAD

**Issue by tintou** [libical/libical#523]
It seems that the generator only takes the `nullable` and now deprecated `allow-none` parameter, it should also handle the `optional` parameter correctly.

**Comment by winterz** [comment]
@tintou I will back port your patch to the 3.0 branch.
please close if this one is done.

**Comment by winterz** [comment]
I'm assuming this is closed as the merges were done more than 6 months ago.
re-open or create a new issue if more needs to be done.
