### ISSUE TITLE
No way to get the exact GEO value as text

### ISSUE THREAD

**Issue by dilyanpalauzov** [libical/libical#531]
When `GEO:49.42612;7.75473` is parsed and converted with icalvalue_geo_as_ical_string_r() back to string, the result is `49.426120;7.754730`.  In the input the precision is 1.1m, in the output the precision is 11cm.

* Provide means to get the value`49.42612;7.75473` from the input.

**Comment by winterz** [comment]
verified.  I'll see what I can do

**Comment by winterz** [comment]
to solve this we could store GEO values internally as strings, not floats

**Comment by ksmurchison** [comment]
That would make sense, as there is an iCalendar extension coming down the pike to allow geo: uris in GEO, e.g.: GEO;VALUE=URI:geo:37.786971,-122.399677;u=35
So we would probably store that as a string anyways

**Comment by winterz** [comment]
Possible fix in PR https://github.com/libical/libical/pull/578
please review and test

**Comment by dilyanpalauzov** [comment]
When the supplied test passes, I do not see a need to test further.

**Comment by ksmurchison** [comment]
@winterz We recently had a client try to store a GEO property where one of the values was 3.035945999999967 and the property was rejected.  I'm wondering is we should increase ICAL_GEO_LEN, or since 8 decimal places has an accuracy of 1.1mm, we just truncate (and round?) these values after 8 decimal places.

Thoughts?

**Comment by dilyanpalauzov** [comment]
<img src="https://imgs.xkcd.com/comics/coordinate_precision.png" alt="https://xkcd.com/2170/">

My understanding is that 5 digits after the decimal comma correspond to 1.1m precision - http://wiki.gis.com/wiki/index.php/Decimal_degrees - and no device can measure higher precision.

**Comment by winterz** [comment]
> @winterz We recently had a client try to store a GEO property where one of the values was 3.035945999999967 and the property was rejected. I'm wondering is we should increase ICAL_GEO_LEN, or since 8 decimal places has an accuracy of 1.1mm, we just truncate (and round?) these values after 8 decimal places.
> 
> Thoughts?

I think truncate and round make sense.

**Comment by ksmurchison** [comment]
@winterz  Another possible issue before I start on this.  Has anyone actually tried this code on Windows?  The documentation for GetNumberFormat() says that the input string must be NULL-terminated and that a leading '+' isn't allowed: https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getnumberformata

My current inclination (being lazy) is to just truncate the value at 15 characters.  And I'll attempt to fix the Windows issue although I can't test it.

#657

**Comment by winterz** [comment]
I just tested 3.0 and master branches on windows (without your patch) and all the regression tests pass.

**Comment by winterz** [comment]
oh, and we should backport this to the 3.0 branch as well.

**Comment by ksmurchison** [comment]
Interesting.  So either we're lucky or the documentation is lying.  I can remove my Windows "fix" from my PR if we don't think its necessary.

**Comment by winterz** [comment]
erg... except ... "- Looking for GetNumberFormat - not found"  from CMake on Windows 10 with msvc2022 in the master branch..  guess I'm not testing GetNumberFormat at all.    anyone want to look at why  in (see ConfigureChecks.cmake)?

**Comment by winterz** [comment]
a couple things: 
* looks like we need to also look for GetNumberFormatEx these days on Windows
* strndup doesn't seem to exist on Windows.  maybe try using icalmemory_strdup() instead

When compiling with GetNumberFormatEx  see these compiler warnings:
```C:\projects\libical\libical\src\libical\icalvalue.c(402): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
C:\projects\libical\libical\src\libical\icalvalue.c(433): warning C4047: 'function': 'LPCWSTR' differs in levels of indirection from 'unsigned long'
C:\projects\libical\libical\src\libical\icalvalue.c(433): warning C4024: 'GetNumberFormatEx': different types for formal and actual parameter 1
C:\projects\libical\libical\src\libical\icalvalue.c(433): warning C4133: 'function': incompatible types - from 'char *' to 'LPCWSTR'
C:\projects\libical\libical\src\libical\icalvalue.c(433): warning C4133: 'function': incompatible types - from 'char *' to 'LPWSTR'
```

then when I ran the regression test it crashed with a heap memory problem.

So then I tried without finding GetNumberFormatEx and using icalmemory_strdup() -> the regression test has failures:
```not ok 1167 - icalproperty_get_value_as_string() works
# test failed: ""
#          at: C:\projects\libical\libical\src\test\regression.c:4396
#      got: 49.43;7.75
# expected: 49.42612;7.75473
ok 1168 - icalparser_parse_string()
BEGIN:VEVENT
GEO:0.00;+0.00
END:VEVENT
not ok 1169 - icalproperty_get_value_as_string() works
# test failed: ""
#          at: C:\projects\libical\libical\src\test\regression.c:4408
#      got: 0.00;+0.00
# expected: -0;+0
BEGIN:VEVENT
X-LIC-ERROR;X-LIC-ERRORTYPE=VALUE-PARSE-ERROR:Can't parse as GEO value in
 GEO property. Removing entire property: -0a\;+0
END:VEVENT
ok 1170 - expected fail icalcomponent_get_first_property()
ok 1171 - icalparser_parse_string()```

Recommend fixing the code to work everywhere without GetNumberFormat (or GetNumberFormatEx) in this patch and then we have a follow-on patch to deal with GetNumberFormat(Ex)

**Comment by ksmurchison** [comment]
@winterz I'm confused.  You're saying that the !defined(HAVE_GETNUMBERFORMAT) code fails on Windows?  Its works fine on my Linux box

**Comment by ksmurchison** [comment]
I force-pushed a change to the Window-specific code to NOT use strndup().  Here are my regression results on Linux:

`########## Test geo precision                       (82) ##########
ok 1170 - icalparser_parse_string()
BEGIN:VEVENT
GEO:49.42612;7.75473
END:VEVENT
ok 1171 - icalproperty_get_value_as_string() works
ok 1172 - icalparser_parse_string()
BEGIN:VEVENT
GEO:-0;+0
END:VEVENT
ok 1173 - icalproperty_get_value_as_string() works
BEGIN:VEVENT
X-LIC-ERROR;X-LIC-ERRORTYPE=VALUE-PARSE-ERROR:Can't parse as GEO value in 
 GEO property. Removing entire property: -0a\;+0
END:VEVENT
ok 1174 - expected fail icalcomponent_get_first_property()
ok 1175 - icalparser_parse_string()
BEGIN:VEVENT
GEO:16.815151515151;+0
END:VEVENT
ok 1176 - icalproperty_get_value_as_string() works
ok 1177 - no memory leaked
`
