### ISSUE TITLE
Discuss: Make `icalrecurrencetype` a reference object?

### ISSUE THREAD

**Issue by minichma** [libical/libical#548]
The `icalrecurrencetype` struct is passed throughout libical by value. This probably has historic reasons, as it doesn't require much memory management and used to be sufficient. But with introduction of rscale, the new `icalrecurrencetype.rscale` attribte was introduced, which points at a dynamically allocated block of memory. The benefit of easy memory management is gone since then, as anyone using the type now needs to manage the referenced memory.

So this is to discuss, whether it would make sense to treat `icalrecurrencetype` as a reference type. This would mean introducing funcs like `icalrecur_new()`, `icalrecur_free()` and `icalrecur_clone()`. Cloning and freeing the rscale memory would be done inside `icalrecur_clone()` and `icalrecur_free()`, which would improve encapsulation and decoupling.

Another benefits would be, that the type could be made more dynamic as a whole over time. Today the size of the type is quite large, which can (and does) cause issues on resource-constrained devices, like embedded ones. By making it a reference type and centralizing the type's memory management within `icalrecur.c`, we could easily make it more dynamic. E.g. we could replace the big static by_xxx arrays with dynamic ones, therefore saving significant amounts of memory (in most cases).

The major downside would be backwards-compatibility. I.e. `icalproperty_new_rrule()` et al. would change their signature, as they would have to take pointers instead of values. Are these functions considered public? This would probably require introducing this only in a new major version, right?

We implemented something like this in a fork foccussed at embedded devices. The main changes (based on a version from 2018) can be seen here (including both, the change to a reference type as well as replacing the static by_xxx arrays):
https://github.com/tapkey/libical/compare/5683dd4..9579d55

If considered beneficial, I'd consider refurbishing the change and contributing it back to libical.

**Comment by winterz** [comment]
Totally agree.  In fact, see #387

**Comment by minichma** [comment]
Thanks for the link! So I'll close this as duplicate. I'll copy my description over as a comment, as some aspects regarding managing the memory of icalrecurrencetype are added.
