### ISSUE TITLE
`USE_32BIT_TIME_T=True` doesn't seem to result in `SIZEOF_TIME_T == 4`

### ISSUE THREAD

**Issue by minichma** [libical/libical#557]
When setting CMake option `-DUSE_32BIT_TIME_T=True` on 32-bit Win32 architectures, the size of `time_t` is forced to 32-bit, so we also expect `SIZEOF_TIME_T` to be set to 4 by CMake, which doesn't seem to be the case.

### Reproduce

Add the following code to `config.h.cmake`:

```c
#if defined(_MSC_VER) && defined(_USE_32BIT_TIME_T) && (SIZEOF_TIME_T != 4)
#error "SIZEOF_TIME_T expected to be 4 but isnt't."
#endif
```

When building with CMake option `-DUSE_32BIT_TIME_T=True` on 32-bit Win32 architectures, a compilation error will be raised.

When checking `sizeof(time_t)`, it's 4 btw.

It seems, that the required Win32 define isn't set while checking the type size.

**Comment by winterz** [comment]
the only reason we had this was for ancient 32-bit MS ( VS2005,maybe ?) compilers that didn't have 32-bit time_t (still using 16 bit time_t I believe)

I doubt libical master will build with vs2005 any longer and we can probably remove this option.

Modern times, I *think* we can assume time_t is always at least 32bits and we should be working towards the goal of making sure all configurations use 64-bit time_t whenever possible.
