### ISSUE TITLE
cmake not working

### ISSUE THREAD

**Issue by gnhartch** [libical/libical#560]
libical won't make the package and i have literally no idea why 

`Determining if files sys/endian.h exist failed with the following output:
Change Dir: /home/buttx/Programs/libical/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_ef906/fast && /usr/bin/make  -f CMakeFiles/cmTC_ef906.dir/build.make CMakeFiles/cmTC_ef906.dir/build
make[1]: Entering directory '/home/buttx/Programs/libical/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ef906.dir/HAVE_SYS_ENDIAN_H.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_ef906.dir/HAVE_SYS_ENDIAN_H.c.o -c /home/buttx/Programs/libical/build/CMakeFiles/CheckIncludeFiles/HAVE_SYS_ENDIAN_H.c
/home/buttx/Programs/libical/build/CMakeFiles/CheckIncludeFiles/HAVE_SYS_ENDIAN_H.c:2:10: fatal error: sys/endian.h: No such file or directory
    2 | #include <sys/endian.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [CMakeFiles/cmTC_ef906.dir/build.make:78: CMakeFiles/cmTC_ef906.dir/HAVE_SYS_ENDIAN_H.c.o] Error 1
make[1]: Leaving directory '/home/buttx/Programs/libical/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_ef906/fast] Error 2

Source:
/* */
#include <sys/endian.h>

int main(void){return 0;}

Determining size of wint_t failed with the following output:
Change Dir: /home/buttx/Programs/libical/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_94a31/fast && /usr/bin/make  -f CMakeFiles/cmTC_94a31.dir/build.make CMakeFiles/cmTC_94a31.dir/build
make[1]: Entering directory '/home/buttx/Programs/libical/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_94a31.dir/SIZEOF_WINT_T.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_94a31.dir/SIZEOF_WINT_T.c.o -c /home/buttx/Programs/libical/build/CMakeFiles/CheckTypeSize/SIZEOF_WINT_T.c
/home/buttx/Programs/libical/build/CMakeFiles/CheckTypeSize/SIZEOF_WINT_T.c:27:22: error: ‘wint_t’ undeclared here (not in a function); did you mean ‘uint8_t’?
   27 | #define SIZE (sizeof(wint_t))
      |                      ^~~~~~
/home/buttx/Programs/libical/build/CMakeFiles/CheckTypeSize/SIZEOF_WINT_T.c:29:12: note: in expansion of macro ‘SIZE’
   29 |   ('0' + ((SIZE / 10000)%10)),
      |            ^~~~
make[1]: *** [CMakeFiles/cmTC_94a31.dir/build.make:78: CMakeFiles/cmTC_94a31.dir/SIZEOF_WINT_T.c.o] Error 1
make[1]: Leaving directory '/home/buttx/Programs/libical/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_94a31/fast] Error 2`

i literally just want to use blueZ but it needs libical as a dependency and now i have to teach myself to code instead of making dinner :D

**Comment by winterz** [comment]
more than likely you are hurting yourself with environment variables that CMake is finding.
look for various settings like CFLAGS, LDFLAGS, etc in your env and try unsetting them.
