### ISSUE TITLE
Docs: add UsingLibical.md to Doxygen

### ISSUE THREAD

**Issue by mcclurgm** [libical/libical#561]
This is just a suggestion, so feel free to close if it doesn't fit with your goals for the docs or anything.

Since Doxygen supports using Markdown files directly as "pages," it's fairly easy to integrate the current "Using Libical" document into the Doxygen apidocs website. A simple version could be done without modifying the document at all, just by adding it to the doxyfile and probably linking to it from `Mainpage.dox` for visibility.

As a newcomer to the library I didn't find that document, which contains most of the conceptual description, until I came to github to report a bug. Putting all the documentation in one place would alleviate that issue by making everything visible together.

Adding the overview to the Doxygen site would also enable linking, so you could include references to the conceptual descriptions from the API docs where relevant (for example, from `icalcomponent`). Again, this could be done without changing the markdown by simply linking to the page. But if you wanted to add more fine grained links, you could add Doxygen header tags to allow linking directly to the Component section from the Component docs, for example. That would break the formatting as displayed on GitHub, however.

If this is something you want, I would be happy to help set it up.

**Comment by winterz** [comment]
totally agree.  would love your help on this.
anything at all to improve the documentation is most welcome.

**Comment by mcclurgm** [comment]
Alright! I've made a rudimentary version on my computer, but it requires hard coding the file into the doxyfile so I need to fix that. Once I have it sorted I'll submit a PR.

Would you like to do what I mentioned about adding header labels? On further research it looks like GitHub Markdown and Doxygen share a syntax for defining them, so the document should still render properly on GitHub. It would break compatibility with other standard renderers though.

**Comment by winterz** [comment]
header labels is a good idea.
yes please

**Comment by winterz** [comment]
https://libical.github.io/libical/apidocs/index.html !
I changed to version 3.1
