### ISSUE TITLE
Embed README.md in the Mainpage.dox

### ISSUE THREAD

**Issue by winterz** [libical/libical#565]
In the Mainpage.dox can we embed (not a link, but the contents) the README.md?

rather than having to duplicate the same info in 2 places

CC: @mcclurgm

**Comment by winterz** [comment]
or maybe the README.md becomes the Mainpage.dox?
In Doxyfile.cmake set:
`USE_MDFILE_AS_MAINPAGE = @CMAKE_SOURCE_DIR@/README.md`

**Comment by mcclurgm** [comment]
The second should work. If you set the right label for the H1, Doxygen will also do that itself. Again note that the second option would break rendering on GitHub. But if that's not a concern once it's available on the apidoc site, then the second is also an option.

**Comment by winterz** [comment]
this is done now
