### ISSUE TITLE
Stable libical-glib for 3.1 release?

### ISSUE THREAD

**Issue by winterz** [libical/libical#574]
can we consider the libical-glib API "stable" for 3.1?

if so, then we can remove the "The libical-glib API is currently unstable... " from the README.md and remove the LIBICAL_GLIB_UNSTABLE_API=1 code

@mcrha ?

**Comment by mcrha** [comment]
True. The libical-glib API is the same stable as the libical's API. If I'm not mistaken, the libical-glib API instability was relevant in time the libical-glib was a new and standalone project. Since the libical-glib is part of the libical itself it voided the meaning.

**Comment by winterz** [comment]
ok, I'll remove LIBICAL_GLIB_UNSTABLE_AP stuff from the 3.1 branch
