### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by winterz** [libical/libical#576]
look at the README at https://github.com/libical/libical
you'll see a couple strange things relating to markdown links.

1. "Libical — an implementation of iCalendar protocols and data formats {#mainpage}"
2. "For a conceptual overview of the library, see [UsingLibical.md](@ref UsingLibical)."  <- and there is no hyperlink created pointing to UsingLibical

**Comment by winterz** [comment]
@mcclurgm   could you take a look?

**Comment by mcclurgm** [comment]
Yes, this is an unfortunate side effect of merging the markdown files for use in Doxygen. The `{#mainpage}` label seems to be required to use a file that's not named `mainpage.md` as the Doxygen homepage. These artifacts will also appear wherever we want to use Doxygen header links in other files, too.

There's some claims on the internet that this style of header label is supported by GitHub Markdown, but that seems to be clearly wrong.

**Comment by mcclurgm** [comment]
I should also note that I've tried to use standard Markdown links, which Doxygen says are supported, but fail on my system. If you link directly to `[UsingLibical](UsingLibical.md)` it fails to generate the link, although that would work properly in GitHub. I haven't figured out why, since the Doxygen documentation claims that it should work.

**Comment by winterz** [comment]
not a big deal. thanks for looking.

**Comment by winterz** [comment]
my Fedora system (where I typically generate the docs) has version 1.9.1
I'm happy to build doxygen 1.9.3 from source if necessary.

Here are the instructions I use when updating the dox => https://github.com/libical/libical/wiki/For-the-Maintainers%3A-Updating-the-API-Documentation-Pages.  I can easily add "make sure to use doxygen 1.9.3 or above".  BTW: do you have write access to that wiki?

**Comment by winterz** [comment]
https://libical.github.io/libical/apidocs/index.html updated just now using doxygen1.9.3.

**Comment by winterz** [comment]
all fixed.
thanks @mcclurgm
