### ISSUE TITLE
Time zone expansion omits current date [sf#58]

### ISSUE THREAD

**Issue by winterz** [libical/libical#58]
Issue seen with all libical versions, including 0.44.
Test case iCal data :
1.VEVENT DTSTART and DTEND includes a TZID tag.
2.VTIMEZONE defines a TZID that has DAYLIGHT and STANDARD data, each of
which defines a RRULE and DTSTART.
3.DTSTART in both STANDARD and DAYLIGHT data is ahead of the DTSTART date
of the VEVENT. This is occurring for events that start before the first
offset switch of the year, prior to the DST switch over (i.e. first few
months of the year).

Time zone expansion performed by libical starts from the current year + 5
years. This leads to the VEVENT start date falling before the first time
zone change in the zone-&gt;changes array, and the offset is returned as 0.

The expanded time zone changes should include the most recent change prior
to the VEVENT start date (in this case from the prior year) so that the
offset is calculated correctly for the start date.

**Comment by ksmurchison** [comment]
I'm not sure I completely understand the description.  Are we talking about icaltimezone_expand_vtimezone() or some other API?

**Comment by ksuther** [comment]
This might not be relevant anymore since time zone expansion is generated using RRULEs by default now (#256, aea01d553d8ac33bb48cf58d81d9211a1c0bcd7a).

**Comment by ksmurchison** [comment]
Can this be closed?  RRULE expansion should be correct and we can do anything if the range of the VTIMEZONE component doesn't include the DTSTART of the VEVENT

**Comment by winterz** [comment]
no objection from me 
@ksuther thoughts? can we close this?

**Comment by ksuther** [comment]
I'd say so, doesn't seem relevant anymore without a specific (and probably odd) use case.
