### ISSUE TITLE
thunderbird calendar error: ThCouldn't find /freeassociation.sourceforge.net

### ISSUE THREAD

**Issue by ghost** [libical/libical#583]
Hello
Since 2 years I systematically have an error on time-zone in thunderbird calendar, but I never found any solution in mozilla forums
_**Fuseau horaire « /freeassociation.sourceforge.net/Europe/Paris » inconnu**_
I suppose that I must change the web site freeassociation.sourceforge.net  but to which web site  and how can I do that in thunderbird

regards

**Comment by mcrha** [comment]
I suppose you can just close this, the reporter deleted the account already.

I do not know much about Thunderbird either. The error reads `Time zone « /freeassociation.sourceforge.net/Europe/Paris » unknown`.

I'd guess, and only guess, the calendar failed to find the libical's `Europe/Paris` builtin timezone for some reason. As the `freeassociation.sourceforge.net` is the current `BUILTIN_TZID_PREFIX`, it might be more Thunderbird's fault, from my point of view.
