### ISSUE TITLE
Tests fail with missing executables

### ISSUE THREAD

**Issue by mcclurgm** [libical/libical#586]
Apologies if this is just me misunderstanding how to run the tests, but I can't get them to run at all.

I use the command `make test` from the build directory. It outputs the following log (a representative snippet copied from `<build>/Temporary/LastTest.log`:

```
42/43 Test: icalrecurtest-r
Command: "/usr/bin/cmake" "-D" "test_cmd=/home/michael/Projekte/libical/build/src/test/icalrecurtest" "-D" "test_args:string=-r" "-D" "output_blessed=/home/michael/Projekte/libical/src/test/icalrecur_withicu_dangi_test.out" "-D" "output_test=/home/michael/Projekte/libical/build/bin/test.out" "-P" "/home/michael/Projekte/libical/cmake/run_test.cmake"
Directory: /home/michael/Projekte/libical/build/bin
"icalrecurtest-r" start time: Sep 01 09:02 MDT
Output:
----------------------------------------------------------
CMake Error at /home/michael/Projekte/libical/cmake/run_test.cmake:31 (message):
  Unable to run test
  '/home/michael/Projekte/libical/build/src/test/icalrecurtest': : shell
  output: No such file or directory!


CMake Error at /home/michael/Projekte/libical/cmake/run_test.cmake:46 (message):
  Output does not match for
  /home/michael/Projekte/libical/src/test/icalrecur_withicu_dangi_test.out
  and /home/michael/Projekte/libical/build/bin/test.out: Files
  "/home/michael/Projekte/libical/src/test/icalrecur_withicu_dangi_test.out"
  to "/home/michael/Projekte/libical/build/bin/test.out" are different.

   : shell output: 1!


<end of output>
Test time =   0.03 sec
----------------------------------------------------------
Test Failed.
"icalrecurtest-r" end time: Sep 01 09:02 MDT
"icalrecurtest-r" time elapsed: 00:00:00
----------------------------------------------------------
```

This looks naively like it's trying to use the name of the test as a source file or executable. A possible culprit is [`src/test/CMakeLists.txt` line 194](https://github.com/libical/libical/blob/b8c2f4cfdf940687e96d1433493012cd8cd0b2e3/src/test/CMakeLists.txt#L194).

**Comment by mcclurgm** [comment]
OK, I think I figured this out. I use fish as my default shell, and when I switched to bash it worked fine. Seems this is user error. Note for anyone who encounters similar issues: it depends on the shell you're using.

**Comment by winterz** [comment]
strange.
I tried to duplicate with 'fish' but didn't see any failures.

I started fish, then ran `mkdir build; cd build; cmake .. && ninja && ninja test`.  worked ok in the 3.0 branch.
oh, maybe this is happening in the master branch ?  I'll try that next

**Comment by winterz** [comment]
works for me in master branch too.
oh well.  I really don't want to ban anyone's favorite shell.

sorry
