### ISSUE TITLE
Since 3.0.15, icalparser_parse_string() is limited to a maximum of 80 lines in the string

### ISSUE THREAD

**Issue by simonmunton** [libical/libical#605]
Commit ca3e2ad introduced a limit on how many lines could be processed in one call to icalparser_parse()

This stops KDE's kalarm program from being able to read the ical files it uses to store its alarms if the file has more than 80 liines. (kalarm uses KDE frameworks kcalendarcore to read the files, which in turn calls icalcomponent_new_from_string() with the whole file in the string, which in turn calls icalparser_parse_string() )

**Comment by winterz** [comment]
are you able to test reverting ca3e2ad983771b90da259994b7a6d7de1fd1abdc
I'll make a 3.0.16 release as necessary. once we find the problematic commit

**Comment by simonmunton** [comment]
I can confirm that reverting commit ca3e2ad allows kalarm to read its ical files successfully

**Comment by aiomaster** [comment]
Same problem with ktimetracker which uses an ical file to store its data. There is no problem when I revert libical to 3.0.14.

**Comment by winterz** [comment]
fixed in eeccee80d0485bdd3951924b294a82e8bc39a5f8
