### ISSUE TITLE
UNTIL of date type should define an inclusive bound [sf#63]

### ISSUE THREAD

**Issue by winterz** [libical/libical#63]
According to rfc 2445:
"The UNTIL rule part defines a date-time value which bounds the recurrence rule in an inclusive manner. If the value specified by UNTIL is synchronized with the specified recurrence, this date or date-time becomes the last instance of the recurrence."

an event with following definition should occur at 20100611 as the last instance, but it returns null time before returning 20100611 when I use icalrecur\_iterator\_next to iterate the recurrence, i.e., 20100610 is returned in the last iteration and then icaltime\_is\_null\_time returns true.
DTSTART;VALUE=DATE:20100524
DTEND;VALUE=DATE:20100525
RRULE:FREQ=DAILY;UNTIL=20100611;WKST=SU

**Comment by ksmurchison** [comment]
This appears to work correctly in master using my test harness:

RRULE:FREQ=DAILY;UNTIL=20100611;WKST=SU
DTSTART:20100524
INSTANCES:20100524,20100525,20100526,20100527,20100528,20100529,20100530,20100531,20100601,20100602,20100603,20100604,20100605,20100606,20100607,20100608,20100609,20100610,20100611

**Comment by winterz** [comment]
closing then
