### ISSUE TITLE
cmake for iOS simulator arm64 failed

### ISSUE THREAD

**Issue by IMCHO** [libical/libical#641]
After I did the following steps, 

1.  add the command in `CMakeLists.txt`
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -arch arm64")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -arch arm64")
```
2. run the command in console
```
cmake .. -GXcode -DCMAKE_SYSTEM_NAME=iOS
```

getting error like below.

```
CMake Error at src/libical-glib/CMakeLists.txt:21 (install):
  install TARGETS given no BUNDLE DESTINATION for MACOSX_BUNDLE executable
  target "ical-glib-src-generator".


CMake Error at src/libical-glib/CMakeLists.txt:88 (include):
  include could not find requested file:

    ICAL_GLIB_SRC_GENERATOR-NOTFOUND
```

**Comment by winterz** [comment]
Please see https://github.com/libical/libical/issues/481

**Comment by IMCHO** [comment]
Still confusing...
Should I need `-DICAL_GLIB_SRC_GENERATOR` flag with full path of `IcalGlibSrcGenerator.cmake`?

> cmake CMakeLists.txt -DIMPORT_ICAL_GLIB_SRC_GENERATOR=...

**Comment by mcrha** [comment]
> Should I need `-DICAL_GLIB_SRC_GENERATOR` flag with full path of `IcalGlibSrcGenerator.cmake`?

The #481 references the wiki page https://github.com/libical/libical/wiki/For-the-Users:-Cross-compiling , where you can see the answer. Beware of the variable names, they are similar, but not the same (evenin your comment, what you wrote is a different name than what you quoted.

I suppose it does not matter now, I'm almost a year late. I suggest to close this and, if needed, discuss further here and reopen only if any new changes will be needed.
