### ISSUE TITLE
Do not fiddle with setlocale() in icalvalue_geo_as_ical_string_r() in master branch

### ISSUE THREAD

**Issue by mcrha** [libical/libical#644]
I guess it left there from times when `struct icalgeotype` used to have `double`-s, but since it is strings in the `master` branch, I suggest to remove the `setlocale()` calls in the `icalvalue_geo_as_ical_string_r()`, because it has no meaning there.

**Comment by winterz** [comment]
@mcrha can you review https://github.com/libical/libical/pull/645

**Comment by mcrha** [comment]
> @mcrha can you review #645

The change looks good to me. The CI has some problems with the MacOS builds, but they are unrelated to the change, from my point of view.

**Comment by winterz** [comment]
thanks.  
yes, I have no idea what's wrong with the mac builders on appveyor.

**Comment by mcrha** [comment]
Looks like an issue with the SQLite package/tarball reference:

```
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.43.0_1
######################################################################### 100.0%
==> Pouring sqlite--3.43.0_1.monterey.bottle.tar.gz
Error: No such file or directory @ rb_sysopen - /Users/appveyor/Library/Caches/Homebrew/downloads/63374848e385597e4a562f3f7637a8193b4c81772e1c7aac2e8617c0395e92aa--sqlite--3.43.0_1.monterey.bottle.tar.gz
Command exited with code 1
Build failed
```
