### ISSUE TITLE
icalrecurtest-r fails with libical-3.0.18 and ICU 75.1

### ISSUE THREAD

**Issue by xry111** [libical/libical#684]
test.out contains:

```
RRULE:RSCALE=RUSSIAN;FREQ=YEARLY
DTSTART:20131025
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=ETHIOPIC;FREQ=YEARLY;BYMONTH=13;BYMONTHDAY=-1;COUNT=6
DTSTART:20140910
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=CHINESE;FREQ=YEARLY;UNTIL=20180101
DTSTART:20130210
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=CHINESE;FREQ=MONTHLY;COUNT=4
DTSTART:20140920
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=ISLAMIC-CIVIL;FREQ=MONTHLY;COUNT=4
DTSTART:20131025
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=ISLAMIC-CIVIL;FREQ=YEARLY;BYMONTH=9;COUNT=5
DTSTART:20130709
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=DANGI;FREQ=YEARLY;BYMONTHDAY=8;BYMONTH=4;UNTIL=20160101
DTSTART:20131025
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=CHINESE;FREQ=YEARLY;BYMONTHDAY=10;BYMONTH=9;COUNT=3
DTSTART:20131025
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=CHINESE;FREQ=YEARLY;BYMONTHDAY=10;BYMONTH=9L;SKIP=OMIT;COUNT=2
DTSTART:20131025
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=CHINESE;FREQ=YEARLY;BYMONTHDAY=10;BYMONTH=4L;SKIP=OMIT;UNTIL=21000101
DTSTART:20131025
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=CHINESE;FREQ=YEARLY;BYMONTHDAY=10;BYMONTH=9L;SKIP=FORWARD;COUNT=3
DTSTART:20131025
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=CHINESE;FREQ=YEARLY;BYMONTHDAY=10;BYMONTH=9L;SKIP=BACKWARD;COUNT=3
DTSTART:20131025
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=CHINESE;FREQ=YEARLY;BYMONTHDAY=10;BYMONTH=9,9L;SKIP=BACKWARD;COUNT=4
DTSTART:20131025
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=CHINESE;FREQ=YEARLY;UNTIL=20200101;INTERVAL=2
DTSTART:20130210
START-AT:20160101
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=HEBREW;FREQ=YEARLY;COUNT=4
DTSTART:20140205
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=HEBREW;FREQ=YEARLY;SKIP=FORWARD;COUNT=4
DTSTART:20140205
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=HEBREW;FREQ=YEARLY;BYMONTH=5L;BYMONTHDAY=8;SKIP=FORWARD;COUNT=5
DTSTART:20140208
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=HEBREW;FREQ=YEARLY;BYMONTH=5L;BYMONTHDAY=30;SKIP=FORWARD;COUNT=5
DTSTART:20140302
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=HEBREW;FREQ=YEARLY;BYMONTH=5L;BYMONTHDAY=-1;SKIP=FORWARD;COUNT=5
DTSTART:20140302
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=HEBREW;FREQ=YEARLY;BYMONTH=5L;BYMONTHDAY=30;SKIP=BACKWARD;COUNT=5
DTSTART:20140302
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=HEBREW;FREQ=YEARLY;BYMONTH=5L;BYMONTHDAY=-1;SKIP=BACKWARD;COUNT=5
DTSTART:20140302
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=YEARLY;COUNT=4
DTSTART:20120229
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=MONTHLY;SKIP=BACKWARD;COUNT=4
DTSTART:20140131
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=MONTHLY;SKIP=FORWARD;COUNT=4
DTSTART:20140131
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=YEARLY;BYMONTH=2;BYMONTHDAY=28,29;SKIP=FORWARD;COUNT=5
DTSTART:20150201
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=MONTHLY;INTERVAL=3;SKIP=FORWARD;COUNT=4
DTSTART:20140131
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=MONTHLY;BYMONTHDAY=31;COUNT=12;SKIP=FORWARD
DTSTART:20150131T000000Z
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=MONTHLY;BYMONTHDAY=-31;COUNT=12;SKIP=FORWARD
DTSTART:20150101T000000Z
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=MONTHLY;BYMONTHDAY=31;COUNT=12;SKIP=BACKWARD
DTSTART:20150131T000000Z
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=MONTHLY;BYMONTHDAY=-31;COUNT=12;SKIP=BACKWARD
DTSTART:20150101T000000Z
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=YEARLY;BYYEARDAY=366;SKIP=FORWARD;COUNT=9
DTSTART:20121231T120000
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=YEARLY;BYYEARDAY=366;SKIP=BACKWARD;COUNT=9
DTSTART:20121231T120000
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=YEARLY;BYYEARDAY=-366;SKIP=FORWARD;COUNT=9
DTSTART:20120101T120000
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented

RRULE:RSCALE=GREGORIAN;FREQ=YEARLY;BYYEARDAY=-366;SKIP=BACKWARD;COUNT=9
DTSTART:20120101T120000
INSTANCES: *** UNIMPLEMENTED: This feature has not been implemented
```

Whoops.  Everything is "not implemented."

I tried:

```diff
--- orig/libical-3.0.18/src/libical/icalrecur.c	2024-03-31 18:26:42.000000000 +0800
+++ libical-3.0.18/src/libical/icalrecur.c	2024-05-06 14:03:57.086714615 +0800
@@ -1125,7 +1125,7 @@
 
     calendars = icalarray_new(sizeof(const char **), 20);
 
-    en = ucal_getKeywordValuesForLocale("calendar", NULL, false, &status);
+    en = ucal_getKeywordValuesForLocale("calendar", "", false, &status);
     while ((cal = uenum_next(en, NULL, &status))) {
         cal = icalmemory_tmp_copy(cal);
         icalarray_append(calendars, &cal);
@@ -1526,7 +1526,7 @@
         }
 
         /* Check if specified calendar is supported */
-        en = ucal_getKeywordValuesForLocale("calendar", NULL, false, &status);
+        en = ucal_getKeywordValuesForLocale("calendar", "", false, &status);
         while ((cal = uenum_next(en, NULL, &status))) {
             if (!strcmp(cal, rule.rscale)) {
                 is_hebrew = !strcmp(rule.rscale, "hebrew");
```

and then only one subtest fails with the change:

```diff
--- bin/test.out	2024-05-06 14:08:04.907708256 +0800
+++ ../src/test/icalrecur_withicu_dangi_test.out	2024-03-31 18:26:42.000000000 +0800
@@ -17,7 +17,7 @@
 
 RRULE:RSCALE=ISLAMIC-CIVIL;FREQ=MONTHLY;COUNT=4
 DTSTART:20131025
-INSTANCES:20131025,20141113,20141213,20150111
+INSTANCES:20131025,20131124,20131224,20140122
 
 RRULE:RSCALE=ISLAMIC-CIVIL;FREQ=YEARLY;BYMONTH=9;COUNT=5
 DTSTART:20130709
```

Wikipedia says Islamic calendar has months of 29 or 30 days so it seems the "new" result makes more sense.

ICU documentation seems unclear if the second argument of `ucal_getKeywordValuesForLocale` can be NULL or not.

**Comment by winterz** [comment]
I'm guessing this has something to do with your locale.
could you tell me what the `locale` command prints for you?

**Comment by xry111** [comment]
```
$ locale
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=
```

I also tried some different locale settings (C.UTF-8, en_US.UTF-8, and just C) but they don't work too.

**Comment by heftig** [comment]
> Wikipedia says Islamic calendar has months of 29 or 30 days so it seems the "new" result makes more sense.

No, the new result is broken. The first interval (2013-10-25 to 2014-11-13) is longer than a year.

**Comment by xry111** [comment]
> I'm also seeing this trying to rebuild libical with icu 75.1 for Arch Linux. The locale doesn't seem to matter. I've tried `C.UTF-8`, `en_US.UTF-8` and `C`.
> 
> > Wikipedia says Islamic calendar has months of 29 or 30 days so it seems the "new" result makes more sense.
> 
> No, the new result is broken. The first interval (2013-10-25 to 2014-11-13) is longer than a year.

Oops stupid I.  I read the diff oppositely.

**Comment by lfos** [comment]
From a brief search, it looks like this behavior (i.e., a `NULL` locale resulting in error) may have been introduced in ICU commit https://github.com/unicode-org/icu/commit/929cd9bb4f8c24e0f41e82f9c18bc1abd8b9019b; I am unclear whether or not that's intended behavior.

**Comment by winterz** [comment]
we could put in a conditional compile on ICU 75.x or higher to use an empty string (instead of a NULL).  I guess.
it's tough when upstream dependencies change their API

would anyone like to work on a patch for that?

**Comment by winterz** [comment]
maybe something like:
```
#if U_ICU_VERSION_MAJOR_NUM >=75
en = ucal_getKeywordValuesForLocale("calendar", "", false, &status);
#else
en = ucal_getKeywordValuesForLocale("calendar", NULL, false, &status);
#endif
```

**Comment by heftig** [comment]
Does ICU <= 74 misbehave if you pass an empty string instead of NULL?

**Comment by winterz** [comment]
> Does ICU <= 74 misbehave if you pass an empty string instead of NULL?

I'm not willing to take that chance in the long-time stable 3.0 branch. so I want a conditional compile there.


In master, I'm more willing to take the gamble.

**Comment by ksmurchison** [comment]
FWIW, ICU 71 seems fine using empty string rather than NULL.  I don't actually recall why I used NULL in the first place.

**Comment by lfos** [comment]
What are the next steps? Can we get xry111's proposed patch merged into master? (This issue is currenly holding up [our migration to ICU 75 at Arch Linux](https://archlinux.org/todo/icu-75/). Happy to help turn it into a git-formatted patch if that's what's missing.)

I'd also like to draw attention back to the other remaining test failure pointed out in the original report. I am not sure I grasp what's happening here but at first glance, contrary to xry111's original comment, the "new" output doesn't look right to me; note that the diff seems to be backwards, i.e., diffing "new vs. old" instead of "old vs. new". The new output seems to have a pretty large jump of almost one year after the first occurrence. Looks like an unrelated issue that needs to be investigated separately? Any ideas?

**Comment by winterz** [comment]
> What are the next steps? Can we get xry111's proposed patch merged into master? (This issue is currenly holding up [our migration to ICU 75 at Arch Linux](https://archlinux.org/todo/icu-75/). Happy to help turn it into a git-formatted patch if that's what's missing.)
> 
> I'd also like to draw attention back to the other remaining test failure pointed out in the original report. I am not sure I grasp what's happening here but at first glance, contrary to xry111's original comment, the "new" output doesn't look right to me; note that the diff seems to be backwards, i.e., diffing "new vs. old" instead of "old vs. new". The new output seems to have a pretty large jump of almost one year after the first occurrence. Looks like an unrelated issue that needs to be investigated separately? Any ideas?

yes I'd like a pull request here so CI can at least test on a few platforms and configurations

**Comment by lfos** [comment]
@winterz Friendly ping.

**Comment by winterz** [comment]
your patch at #690 says "partial fix"  
I assumed you weren't done.

are all the tests working with your patch? iirc, there was still 1 failure

also.. I'm scared to break for people using older ICU libraries.  I'd be happier with a conditional compile on v75 or above.
@ksmurchison unless you think this patch is perfectly safe for older ICUs.

**Comment by ksmurchison** [comment]
I tested the patch locally with ICU 71 and it works. I haven't tried other versions but I expect that it would be fine.

**Comment by awilfox** [comment]
The "1 failure" is in calculating Islamic months:

```diff
-INSTANCES:20131025,20131124,20131224,20140122
+INSTANCES:20131025,20141113,20141213,20150111
```

And I have traced this back with `git bisect`: unicode-org/icu@d43d216febe18d37ad840cbac3f953b989b65965 is the first bad commit.  So this is not a libical bug.

**Comment by heftig** [comment]
This part looks broken:

https://github.com/unicode-org/icu/commit/d43d216febe18d37ad840cbac3f953b989b65965#diff-3e7d6ce307054e60f99c19c115fc4016029ea131de563f75f8a1ee1035d15fefR477-R481

```diff
     if (month > 11) {
         eyear += (month / 12);
+        if (uprv_add32_overflow(eyear, (month / 12), &eyear)) {
+            status = U_ILLEGAL_ARGUMENT_ERROR;
+            return 0;
+        }
         month %= 12;
     } else if (month < 0) {
```

It duplicates the addition instead of replacing it with overflow-safe code.

**Comment by awilfox** [comment]
That is exactly the issue.  Applying [islamic-calendar.patch](https://github.com/user-attachments/files/16577684/islamic-calendar.patch) to ICU 75 fixes the issue.  We are going to bring this upstream in the morning.

**Comment by winterz** [comment]
I believe we can close this issue now.
agreed?

**Comment by xry111** [comment]
Agreed but let's put a link to the ICU bug report once it's created.

**Comment by xry111** [comment]
It seems ICU 76.1 contains the fix.

**Comment by winterz** [comment]
@xry111 thanks for handling
