### ISSUE TITLE
RECUR values ignore integers in BYDAY clauses, ie 'FREQ=MONTHLY;BYDAY=-1SU'

### ISSUE THREAD

**Issue by winterz** [libical/libical#777]
Found in the old TODO file:
`RECUR values ignore integers in BYDAY clauses, ie 'FREQ=MONTHLY;BYDAY=-1SU'`

still valid?

**Comment by ksmurchison** [comment]
No, its no longer valid.  icalrecur_test.c has stuff like this:
`    /* Every other month on the first and last Sunday of the month
       for 10 occurrences */
    {"19970907T090000",
     "FREQ=MONTHLY;INTERVAL=2;COUNT=10;BYDAY=1SU,-1SU",
     NULL},
`

**Comment by winterz** [comment]
thanks.
closing
