### ISSUE TITLE
Restrictions code does not catch lack of DTEND or DURATION

### ISSUE THREAD

**Issue by winterz** [libical/libical#778]
Found in the old TODO file
`Restrictions code does not catch lack of DTEND or DURATION`

still valid?

**Comment by ksmurchison** [comment]
This is invalid.  DTEND and DURATION are both optional.  They just can't be used together, which IS caught by the restrictions code.

`For cases where a "VEVENT" calendar component
      specifies a "DTSTART" property with a DATE value type but no
      "DTEND" nor "DURATION" property, the event's duration is taken to
      be one day.  For cases where a "VEVENT" calendar component
      specifies a "DTSTART" property with a DATE-TIME value type but no
      "DTEND" property, the event ends on the same calendar date and
      time of day specified by the "DTSTART" property.`

**Comment by winterz** [comment]
ack. closing
