### ISSUE TITLE
`BYWEEKNO` inconsistent behavior when built without libicu

### ISSUE THREAD

**Issue by minichma** [libical/libical#782]
The following test case succeeds when built with ICU but fails without:

```c
void test_weekno_with_dayno(void)
{
    struct icalrecurrencetype *recur = icalrecurrencetype_new_from_string("FREQ=YEARLY;BYWEEKNO=6;BYDAY=TU;WKST=TH;UNTIL=20210612T000000Z");
    icalrecur_iterator *it = icalrecur_iterator_new(recur, icaltime_from_string("20180206T080001"));
    icalrecurrencetype_unref(recur);

    icaltimetype t;
    
    t = icaltime_from_string("20180213T080001");
    ok("next recurrence is 20180213T080001", icaltime_compare(icalrecur_iterator_next(it), t) == 0);
    t = icaltime_from_string("20190212T080001");
    ok("next recurrence is 20190212T080001", icaltime_compare(icalrecur_iterator_next(it), t) == 0);
    t = icaltime_from_string("20200211T080001");
    ok("next recurrence is 20200211T080001", icaltime_compare(icalrecur_iterator_next(it), t) == 0);
    t = icaltime_from_string("20210209T080001");
    ok("next recurrence is 20210209T080001", icaltime_compare(icalrecur_iterator_next(it), t) == 0);
    
    icalrecur_iterator_free(it);
}
```

In particular the instance `20200211T080001` is missing when run from a build with `HAVE_LIBICU` undefined. It seems that the behavior without ICE is wrong, i.e. `20200211T080001` is a correct recurrence and should be returned.

**Comment by winterz** [comment]
which brings up the issue: should we require libicu now.

note that we have vcpkg support now so Windows people can use that to install libcu pretty easily.

**Comment by minichma** [comment]
Hm, I'm quite happy that there's support for building without libicu, as in our projects we use the lib on a small ARM Cortex M MCU, where we don't have the required resources available.

**Comment by winterz** [comment]
ack. 
no problem. we can keep the libicu dependency optional

**Comment by ksmurchison** [comment]
I will try to give this a look this week, but I'm at a conference through Thu, so no promises.
