### ISSUE TITLE
Recursive crash in icaltimezone_load_builtin_timezone [sf#80]

### ISSUE THREAD

**Issue by winterz** [libical/libical#80]
When converting a time to a time with zone, the code will incorrectly recuse causing a crash.  Logic when the recursion starts is shown in the call stack below

icaltime_convert_to_zone
icaltimezone_convert_time
icaltimezone_get_utc_offset_of_utc_time
icaltimezone_ensure_coverage
icaltimezone_load_builtin_timezone
icalcomponent_remove_component
icaltimezone_get_component
icaltimezone_load_builtin_timezone
...

So, the problem is that during the icalcomponent_remove_component() call it will call the icaltimezone_load_builtin_timezone again.

**Comment by LeoPengNekuros** [comment]
Windows x86 system may have same issue here, but windows x64 system looks fine.
