### ISSUE TITLE
Allow building glib-docs, gobject-inspection and vapi in STATIC_ONLY mode

### ISSUE THREAD

**Issue by winterz** [libical/libical#831]
Currently the build system errors out for the user telling them that static only builds are unsupported 
if GOBJECT_INTROSPECTION or ICAL_GLIB_VAPI or ICAL_BUILD_DOCS are ON in STATIC_ONLY mode.

we do this because the build fails due to something with g-ir-scanner complaining that it can't file the  ical library.

**Comment by tintou** [comment]
The introspection is using libffi and is not really usable with static libraries. I'm unsure that it is a practical use-case so I'm tempted to say that it doesn't work by design.

**Comment by winterz** [comment]
ok, thanks for the feedback.
closing
