### ISSUE TITLE
icalcomponent_foreach_recurrence() misses recurrences if called with a icaltime with is_date=1

### ISSUE THREAD

**Issue by psychon** [libical/libical#833]
Patch showing the behaviour that this is about (based on release 3.0.18):
```diff
diff --git a/src/libical/icalcomponent.c b/src/libical/icalcomponent.c
index c89f4cfd..4546e605 100644
--- a/src/libical/icalcomponent.c
+++ b/src/libical/icalcomponent.c
@@ -865,6 +865,7 @@ void icalcomponent_foreach_recurrence(icalcomponent *comp,
 
             /* make sure we include any recurrence that ends in timespan */
             icaltime_adjust(&mystart, 0, 0, 0, -(int)(long)dtduration);
+            printf("Adding %ld to %s results in new start of %s\n", -(long)dtduration, icaltime_as_ical_string(start), icaltime_as_ical_string(mystart));
             icalrecur_iterator_set_start(rrule_itr, mystart);
         }
 
diff --git a/src/test/regression.c b/src/test/regression.c
index 0b36000b..3cf91a32 100644
--- a/src/test/regression.c
+++ b/src/test/regression.c
@@ -602,6 +602,43 @@ int test_component_foreach_parameterized(int startOffsSec, int endOffsSec, int e
     return 0;
 }
 
+void test_hack_for_bug_report(void)
+{
+    const char *calStr =
+        "BEGIN:VCALENDAR\n"
+        "BEGIN:VEVENT\n"
+        "DTSTART:20240323T010000Z\n"
+        "DTEND:20240324T200000Z\n"
+        "RRULE:FREQ=WEEKLY\n"
+        "END:VEVENT\n"
+        "END:VCALENDAR\n";
+
+    icalcomponent *calendar = icalparser_parse_string(calStr);
+    icalcomponent *event = icalcomponent_get_first_component(calendar, ICAL_VEVENT_COMPONENT);
+    for (int is_date = 0; is_date < 2; is_date++) {
+        printf("Testing with is_date=%d\n", is_date);
+
+        // 2024-03-24 00:00 UTC to 2024-03-30 00:00 UTC
+        struct icaltimetype t_start = icaltime_from_timet_with_zone(1711238400, is_date, NULL);
+        struct icaltimetype t_end = icaltime_from_timet_with_zone(1711756800, is_date, NULL);
+
+        // Check that this is really exactly midnight.
+        int_is("start hour", t_start.hour, 0);
+        int_is("end hour", t_end.hour, 0);
+        int_is("start minute", t_start.minute, 0);
+        int_is("end minute", t_end.minute, 0);
+        int_is("start second", t_start.second, 0);
+        int_is("end second", t_end.second, 0);
+
+        int found = 0;
+        icalcomponent_foreach_recurrence(event, t_start, t_end, test_component_foreach_callback, &found);
+        int_is("Occurs", found, 1);
+
+        puts("Done with test");
+    }
+    icalcomponent_free(calendar);
+}
+
 void test_component_foreach(void)
 {
     const char *calStr =
@@ -5274,6 +5311,8 @@ int main(int argc, char *argv[])
     test_run("Test icalcomponent_vanew with lastmodified property", test_icalcomponent_with_lastmodified, do_test, do_header);
     test_run("Test attendees", test_attendees, do_test, do_header);
 
+    test_run("hack for bug report", test_hack_for_bug_report, do_test, do_header);
+
     /** OPTIONAL TESTS go here... **/
 
 #if defined(WITH_CXX_BINDINGS)
```
Relevant output when running `bin/regression`:
```
########## hack for bug report                      (80) ##########
Testing with is_date=0
ok 864 - start hour
ok 865 - end hour
ok 866 - start minute
ok 867 - end minute
ok 868 - start second
ok 869 - end second
Adding -154800 to 20240324T000000 results in new start of 20240322T050000
ok 870 - Occurs
Done with test
Testing with is_date=1
ok 871 - start hour
ok 872 - end hour
ok 873 - start minute
ok 874 - end minute
ok 875 - start second
ok 876 - end second
Adding -154800 to 20240324 results in new start of 20240324
not ok 877 - Occurs
# test failed: ""
#          at: src/test/regression.c:635
#      got: 0
# expected: 1
Done with test
```
As you can see, when calling `icalcomponent_foreach_recurrence` with an `icaltime` with `is_date=1`, this code misses a recurrence of the event. This is because the code where I added a `printf` takes the event duration (in this case 43 hours) as a value in seconds and passes it to `icaltime_adjust(&mystart, 0, 0, 0, -43*60*60);`. This function then just does nothing here: https://github.com/libical/libical/blob/80045d9c46006ccdbd8d10349edd607974eb095b/src/libical/icaltime.c#L760-L762
Figuring this out took me quite some time.

Ideas for a fix:
- Make `icalcomponent_foreach_recurrence()` reject `start` or `end` being times (e.g. via some `icalerror_set_errno()` plus an early return)
- Make `icalcomponent_foreach_recurrence()` silently set `.is_date = 0` on its `start` and `end` parameters. Dunno if this really works, but I guess dates should always have their hour, minute, second components set to zero...?
- Somehow normalise the duration in `icalcomponent_foreach_recurrence()`. E.g.: `int one_day = 24*60*60; int days = (dtduration + one_day - 1) / one_day; int seconds = dtduration - days * one_day; icaltime_adjust(&mystart, -days, 0, 0, -seconds);`
- Make `icaltime_adjust()` not ignore its second parameter if it is more than a day in seconds. Dunno what the desired behaviour would be (round up or down?) nor do I doubt that this change in behaviour is a good idea.
- Just leave the behaviour as-is and somehow document this case as unsupported? (Dunno if there is anything else that might have a problem with dates)

**Comment by winterz** [comment]
@minichma @ksmurchison  any chance you have time to look at this one soon? 
it would be nice to have for release 3.0.19

**Comment by minichma** [comment]
I will try to find some time at the weekend.

**Comment by minichma** [comment]
I'm not quite sure, whether the best solution would be to disallow start/end being `DATE`-only altogether or just silently converting to date-time. I drafted a PR implementing the latter for compatibility reasons, but maybe, given the fact that v4 is upcoming, we might decide against compatibility and just disallow date-only. TBD.

Another issue fixed is that the calculation of durations of DATE-only events was faulty, i.e. (1 day - 1s) was incorrectly added to the duration, which resulted in incorrect results.

Another shortcoming of the function is the fact, that we don't differentiate between nominal durations (if specified via `DURATION` and exact durations (if specified via `DTEND`), which is tracked in #630, but I didn't address that, except for a comment in KnownLimitaitons.md.
